// Code generated by ent, DO NOT EDIT.

package enrollments

import (
	"lms-api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldUserID, v))
}

// CourseID applies equality check predicate on the "course_id" field. It's identical to CourseIDEQ.
func CourseID(v int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldCourseID, v))
}

// ProgressPercent applies equality check predicate on the "progress_percent" field. It's identical to ProgressPercentEQ.
func ProgressPercent(v float64) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldProgressPercent, v))
}

// EnrolledAt applies equality check predicate on the "enrolled_at" field. It's identical to EnrolledAtEQ.
func EnrolledAt(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldEnrolledAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotIn(FieldUserID, vs...))
}

// CourseIDEQ applies the EQ predicate on the "course_id" field.
func CourseIDEQ(v int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldCourseID, v))
}

// CourseIDNEQ applies the NEQ predicate on the "course_id" field.
func CourseIDNEQ(v int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNEQ(FieldCourseID, v))
}

// CourseIDIn applies the In predicate on the "course_id" field.
func CourseIDIn(vs ...int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIn(FieldCourseID, vs...))
}

// CourseIDNotIn applies the NotIn predicate on the "course_id" field.
func CourseIDNotIn(vs ...int) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotIn(FieldCourseID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotIn(FieldStatus, vs...))
}

// ProgressPercentEQ applies the EQ predicate on the "progress_percent" field.
func ProgressPercentEQ(v float64) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldProgressPercent, v))
}

// ProgressPercentNEQ applies the NEQ predicate on the "progress_percent" field.
func ProgressPercentNEQ(v float64) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNEQ(FieldProgressPercent, v))
}

// ProgressPercentIn applies the In predicate on the "progress_percent" field.
func ProgressPercentIn(vs ...float64) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIn(FieldProgressPercent, vs...))
}

// ProgressPercentNotIn applies the NotIn predicate on the "progress_percent" field.
func ProgressPercentNotIn(vs ...float64) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotIn(FieldProgressPercent, vs...))
}

// ProgressPercentGT applies the GT predicate on the "progress_percent" field.
func ProgressPercentGT(v float64) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGT(FieldProgressPercent, v))
}

// ProgressPercentGTE applies the GTE predicate on the "progress_percent" field.
func ProgressPercentGTE(v float64) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGTE(FieldProgressPercent, v))
}

// ProgressPercentLT applies the LT predicate on the "progress_percent" field.
func ProgressPercentLT(v float64) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLT(FieldProgressPercent, v))
}

// ProgressPercentLTE applies the LTE predicate on the "progress_percent" field.
func ProgressPercentLTE(v float64) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLTE(FieldProgressPercent, v))
}

// EnrolledAtEQ applies the EQ predicate on the "enrolled_at" field.
func EnrolledAtEQ(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldEnrolledAt, v))
}

// EnrolledAtNEQ applies the NEQ predicate on the "enrolled_at" field.
func EnrolledAtNEQ(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNEQ(FieldEnrolledAt, v))
}

// EnrolledAtIn applies the In predicate on the "enrolled_at" field.
func EnrolledAtIn(vs ...time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIn(FieldEnrolledAt, vs...))
}

// EnrolledAtNotIn applies the NotIn predicate on the "enrolled_at" field.
func EnrolledAtNotIn(vs ...time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotIn(FieldEnrolledAt, vs...))
}

// EnrolledAtGT applies the GT predicate on the "enrolled_at" field.
func EnrolledAtGT(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGT(FieldEnrolledAt, v))
}

// EnrolledAtGTE applies the GTE predicate on the "enrolled_at" field.
func EnrolledAtGTE(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGTE(FieldEnrolledAt, v))
}

// EnrolledAtLT applies the LT predicate on the "enrolled_at" field.
func EnrolledAtLT(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLT(FieldEnrolledAt, v))
}

// EnrolledAtLTE applies the LTE predicate on the "enrolled_at" field.
func EnrolledAtLTE(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLTE(FieldEnrolledAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Enrollments {
	return predicate.Enrollments(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUsers applies the HasEdge predicate on the "Users" edge.
func HasUsers() predicate.Enrollments {
	return predicate.Enrollments(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "Users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.Users) predicate.Enrollments {
	return predicate.Enrollments(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCourses applies the HasEdge predicate on the "Courses" edge.
func HasCourses() predicate.Enrollments {
	return predicate.Enrollments(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CoursesTable, CoursesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCoursesWith applies the HasEdge predicate on the "Courses" edge with a given conditions (other predicates).
func HasCoursesWith(preds ...predicate.Courses) predicate.Enrollments {
	return predicate.Enrollments(func(s *sql.Selector) {
		step := newCoursesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Enrollments) predicate.Enrollments {
	return predicate.Enrollments(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Enrollments) predicate.Enrollments {
	return predicate.Enrollments(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Enrollments) predicate.Enrollments {
	return predicate.Enrollments(sql.NotPredicates(p))
}
