// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lms-api/ent/certificates"
	"lms-api/ent/courses"
	"lms-api/ent/users"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Certificates is the model entity for the Certificates schema.
type Certificates struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// CourseID holds the value of the "course_id" field.
	CourseID int `json:"course_id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt time.Time `json:"issued_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CertificatesQuery when eager-loading is set.
	Edges        CertificatesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CertificatesEdges holds the relations/edges for other nodes in the graph.
type CertificatesEdges struct {
	// Users holds the value of the Users edge.
	Users *Users `json:"Users,omitempty"`
	// Courses holds the value of the Courses edge.
	Courses *Courses `json:"Courses,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CertificatesEdges) UsersOrErr() (*Users, error) {
	if e.Users != nil {
		return e.Users, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: users.Label}
	}
	return nil, &NotLoadedError{edge: "Users"}
}

// CoursesOrErr returns the Courses value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CertificatesEdges) CoursesOrErr() (*Courses, error) {
	if e.Courses != nil {
		return e.Courses, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: courses.Label}
	}
	return nil, &NotLoadedError{edge: "Courses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Certificates) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case certificates.FieldID, certificates.FieldUserID, certificates.FieldCourseID:
			values[i] = new(sql.NullInt64)
		case certificates.FieldCode:
			values[i] = new(sql.NullString)
		case certificates.FieldIssuedAt, certificates.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Certificates fields.
func (_m *Certificates) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case certificates.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case certificates.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case certificates.FieldCourseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field course_id", values[i])
			} else if value.Valid {
				_m.CourseID = int(value.Int64)
			}
		case certificates.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case certificates.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = value.Time
			}
		case certificates.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Certificates.
// This includes values selected through modifiers, order, etc.
func (_m *Certificates) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "Users" edge of the Certificates entity.
func (_m *Certificates) QueryUsers() *UsersQuery {
	return NewCertificatesClient(_m.config).QueryUsers(_m)
}

// QueryCourses queries the "Courses" edge of the Certificates entity.
func (_m *Certificates) QueryCourses() *CoursesQuery {
	return NewCertificatesClient(_m.config).QueryCourses(_m)
}

// Update returns a builder for updating this Certificates.
// Note that you need to call Certificates.Unwrap() before calling this method if this Certificates
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Certificates) Update() *CertificatesUpdateOne {
	return NewCertificatesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Certificates entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Certificates) Unwrap() *Certificates {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Certificates is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Certificates) String() string {
	var builder strings.Builder
	builder.WriteString("Certificates(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("course_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CourseID))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("issued_at=")
	builder.WriteString(_m.IssuedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CertificatesSlice is a parsable slice of Certificates.
type CertificatesSlice []*Certificates
