// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-api/ent/categories"
	"lms-api/ent/certificates"
	"lms-api/ent/courses"
	"lms-api/ent/enrollments"
	"lms-api/ent/lessonprogresses"
	"lms-api/ent/lessons"
	"lms-api/ent/predicate"
	"lms-api/ent/quizzes"
	"lms-api/ent/sections"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CoursesUpdate is the builder for updating Courses entities.
type CoursesUpdate struct {
	config
	hooks    []Hook
	mutation *CoursesMutation
}

// Where appends a list predicates to the CoursesUpdate builder.
func (_u *CoursesUpdate) Where(ps ...predicate.Courses) *CoursesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoursesUpdate) SetDeletedAt(v time.Time) *CoursesUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillableDeletedAt(v *time.Time) *CoursesUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoursesUpdate) ClearDeletedAt() *CoursesUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *CoursesUpdate) SetCategoryID(v int) *CoursesUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillableCategoryID(v *int) *CoursesUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *CoursesUpdate) SetTitle(v string) *CoursesUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillableTitle(v *string) *CoursesUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *CoursesUpdate) SetSlug(v string) *CoursesUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillableSlug(v *string) *CoursesUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CoursesUpdate) SetDescription(v string) *CoursesUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillableDescription(v *string) *CoursesUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CoursesUpdate) ClearDescription() *CoursesUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetThumbnail sets the "thumbnail" field.
func (_u *CoursesUpdate) SetThumbnail(v string) *CoursesUpdate {
	_u.mutation.SetThumbnail(v)
	return _u
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillableThumbnail(v *string) *CoursesUpdate {
	if v != nil {
		_u.SetThumbnail(*v)
	}
	return _u
}

// ClearThumbnail clears the value of the "thumbnail" field.
func (_u *CoursesUpdate) ClearThumbnail() *CoursesUpdate {
	_u.mutation.ClearThumbnail()
	return _u
}

// SetPrice sets the "price" field.
func (_u *CoursesUpdate) SetPrice(v float64) *CoursesUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillablePrice(v *float64) *CoursesUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *CoursesUpdate) AddPrice(v float64) *CoursesUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetLevel sets the "level" field.
func (_u *CoursesUpdate) SetLevel(v courses.Level) *CoursesUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillableLevel(v *courses.Level) *CoursesUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CoursesUpdate) SetStatus(v courses.Status) *CoursesUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillableStatus(v *courses.Status) *CoursesUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalLessons sets the "total_lessons" field.
func (_u *CoursesUpdate) SetTotalLessons(v int) *CoursesUpdate {
	_u.mutation.ResetTotalLessons()
	_u.mutation.SetTotalLessons(v)
	return _u
}

// SetNillableTotalLessons sets the "total_lessons" field if the given value is not nil.
func (_u *CoursesUpdate) SetNillableTotalLessons(v *int) *CoursesUpdate {
	if v != nil {
		_u.SetTotalLessons(*v)
	}
	return _u
}

// AddTotalLessons adds value to the "total_lessons" field.
func (_u *CoursesUpdate) AddTotalLessons(v int) *CoursesUpdate {
	_u.mutation.AddTotalLessons(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoursesUpdate) SetUpdatedAt(v time.Time) *CoursesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCategoriesID sets the "Categories" edge to the Categories entity by ID.
func (_u *CoursesUpdate) SetCategoriesID(id int) *CoursesUpdate {
	_u.mutation.SetCategoriesID(id)
	return _u
}

// SetCategories sets the "Categories" edge to the Categories entity.
func (_u *CoursesUpdate) SetCategories(v *Categories) *CoursesUpdate {
	return _u.SetCategoriesID(v.ID)
}

// AddSectionIDs adds the "Sections" edge to the Sections entity by IDs.
func (_u *CoursesUpdate) AddSectionIDs(ids ...int) *CoursesUpdate {
	_u.mutation.AddSectionIDs(ids...)
	return _u
}

// AddSections adds the "Sections" edges to the Sections entity.
func (_u *CoursesUpdate) AddSections(v ...*Sections) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSectionIDs(ids...)
}

// AddLessonIDs adds the "Lessons" edge to the Lessons entity by IDs.
func (_u *CoursesUpdate) AddLessonIDs(ids ...int) *CoursesUpdate {
	_u.mutation.AddLessonIDs(ids...)
	return _u
}

// AddLessons adds the "Lessons" edges to the Lessons entity.
func (_u *CoursesUpdate) AddLessons(v ...*Lessons) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLessonIDs(ids...)
}

// AddQuizzeIDs adds the "Quizzes" edge to the Quizzes entity by IDs.
func (_u *CoursesUpdate) AddQuizzeIDs(ids ...int) *CoursesUpdate {
	_u.mutation.AddQuizzeIDs(ids...)
	return _u
}

// AddQuizzes adds the "Quizzes" edges to the Quizzes entity.
func (_u *CoursesUpdate) AddQuizzes(v ...*Quizzes) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuizzeIDs(ids...)
}

// AddEnrollmentIDs adds the "Enrollments" edge to the Enrollments entity by IDs.
func (_u *CoursesUpdate) AddEnrollmentIDs(ids ...int) *CoursesUpdate {
	_u.mutation.AddEnrollmentIDs(ids...)
	return _u
}

// AddEnrollments adds the "Enrollments" edges to the Enrollments entity.
func (_u *CoursesUpdate) AddEnrollments(v ...*Enrollments) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnrollmentIDs(ids...)
}

// AddLessonProgressIDs adds the "LessonProgresses" edge to the LessonProgresses entity by IDs.
func (_u *CoursesUpdate) AddLessonProgressIDs(ids ...int) *CoursesUpdate {
	_u.mutation.AddLessonProgressIDs(ids...)
	return _u
}

// AddLessonProgresses adds the "LessonProgresses" edges to the LessonProgresses entity.
func (_u *CoursesUpdate) AddLessonProgresses(v ...*LessonProgresses) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLessonProgressIDs(ids...)
}

// AddCertificateIDs adds the "Certificates" edge to the Certificates entity by IDs.
func (_u *CoursesUpdate) AddCertificateIDs(ids ...int) *CoursesUpdate {
	_u.mutation.AddCertificateIDs(ids...)
	return _u
}

// AddCertificates adds the "Certificates" edges to the Certificates entity.
func (_u *CoursesUpdate) AddCertificates(v ...*Certificates) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCertificateIDs(ids...)
}

// Mutation returns the CoursesMutation object of the builder.
func (_u *CoursesUpdate) Mutation() *CoursesMutation {
	return _u.mutation
}

// ClearCategories clears the "Categories" edge to the Categories entity.
func (_u *CoursesUpdate) ClearCategories() *CoursesUpdate {
	_u.mutation.ClearCategories()
	return _u
}

// ClearSections clears all "Sections" edges to the Sections entity.
func (_u *CoursesUpdate) ClearSections() *CoursesUpdate {
	_u.mutation.ClearSections()
	return _u
}

// RemoveSectionIDs removes the "Sections" edge to Sections entities by IDs.
func (_u *CoursesUpdate) RemoveSectionIDs(ids ...int) *CoursesUpdate {
	_u.mutation.RemoveSectionIDs(ids...)
	return _u
}

// RemoveSections removes "Sections" edges to Sections entities.
func (_u *CoursesUpdate) RemoveSections(v ...*Sections) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSectionIDs(ids...)
}

// ClearLessons clears all "Lessons" edges to the Lessons entity.
func (_u *CoursesUpdate) ClearLessons() *CoursesUpdate {
	_u.mutation.ClearLessons()
	return _u
}

// RemoveLessonIDs removes the "Lessons" edge to Lessons entities by IDs.
func (_u *CoursesUpdate) RemoveLessonIDs(ids ...int) *CoursesUpdate {
	_u.mutation.RemoveLessonIDs(ids...)
	return _u
}

// RemoveLessons removes "Lessons" edges to Lessons entities.
func (_u *CoursesUpdate) RemoveLessons(v ...*Lessons) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLessonIDs(ids...)
}

// ClearQuizzes clears all "Quizzes" edges to the Quizzes entity.
func (_u *CoursesUpdate) ClearQuizzes() *CoursesUpdate {
	_u.mutation.ClearQuizzes()
	return _u
}

// RemoveQuizzeIDs removes the "Quizzes" edge to Quizzes entities by IDs.
func (_u *CoursesUpdate) RemoveQuizzeIDs(ids ...int) *CoursesUpdate {
	_u.mutation.RemoveQuizzeIDs(ids...)
	return _u
}

// RemoveQuizzes removes "Quizzes" edges to Quizzes entities.
func (_u *CoursesUpdate) RemoveQuizzes(v ...*Quizzes) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuizzeIDs(ids...)
}

// ClearEnrollments clears all "Enrollments" edges to the Enrollments entity.
func (_u *CoursesUpdate) ClearEnrollments() *CoursesUpdate {
	_u.mutation.ClearEnrollments()
	return _u
}

// RemoveEnrollmentIDs removes the "Enrollments" edge to Enrollments entities by IDs.
func (_u *CoursesUpdate) RemoveEnrollmentIDs(ids ...int) *CoursesUpdate {
	_u.mutation.RemoveEnrollmentIDs(ids...)
	return _u
}

// RemoveEnrollments removes "Enrollments" edges to Enrollments entities.
func (_u *CoursesUpdate) RemoveEnrollments(v ...*Enrollments) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnrollmentIDs(ids...)
}

// ClearLessonProgresses clears all "LessonProgresses" edges to the LessonProgresses entity.
func (_u *CoursesUpdate) ClearLessonProgresses() *CoursesUpdate {
	_u.mutation.ClearLessonProgresses()
	return _u
}

// RemoveLessonProgressIDs removes the "LessonProgresses" edge to LessonProgresses entities by IDs.
func (_u *CoursesUpdate) RemoveLessonProgressIDs(ids ...int) *CoursesUpdate {
	_u.mutation.RemoveLessonProgressIDs(ids...)
	return _u
}

// RemoveLessonProgresses removes "LessonProgresses" edges to LessonProgresses entities.
func (_u *CoursesUpdate) RemoveLessonProgresses(v ...*LessonProgresses) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLessonProgressIDs(ids...)
}

// ClearCertificates clears all "Certificates" edges to the Certificates entity.
func (_u *CoursesUpdate) ClearCertificates() *CoursesUpdate {
	_u.mutation.ClearCertificates()
	return _u
}

// RemoveCertificateIDs removes the "Certificates" edge to Certificates entities by IDs.
func (_u *CoursesUpdate) RemoveCertificateIDs(ids ...int) *CoursesUpdate {
	_u.mutation.RemoveCertificateIDs(ids...)
	return _u
}

// RemoveCertificates removes "Certificates" edges to Certificates entities.
func (_u *CoursesUpdate) RemoveCertificates(v ...*Certificates) *CoursesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCertificateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CoursesUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoursesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CoursesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoursesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoursesUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if courses.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized courses.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := courses.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CoursesUpdate) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := courses.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Courses.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := courses.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Courses.status": %w`, err)}
		}
	}
	if _u.mutation.CategoriesCleared() && len(_u.mutation.CategoriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Courses.Categories"`)
	}
	return nil
}

func (_u *CoursesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(courses.Table, courses.Columns, sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(courses.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(courses.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(courses.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(courses.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(courses.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(courses.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Thumbnail(); ok {
		_spec.SetField(courses.FieldThumbnail, field.TypeString, value)
	}
	if _u.mutation.ThumbnailCleared() {
		_spec.ClearField(courses.FieldThumbnail, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(courses.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(courses.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(courses.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(courses.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TotalLessons(); ok {
		_spec.SetField(courses.FieldTotalLessons, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalLessons(); ok {
		_spec.AddField(courses.FieldTotalLessons, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(courses.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   courses.CategoriesTable,
			Columns: []string{courses.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   courses.CategoriesTable,
			Columns: []string{courses.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.SectionsTable,
			Columns: []string{courses.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSectionsIDs(); len(nodes) > 0 && !_u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.SectionsTable,
			Columns: []string{courses.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.SectionsTable,
			Columns: []string{courses.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonsTable,
			Columns: []string{courses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLessonsIDs(); len(nodes) > 0 && !_u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonsTable,
			Columns: []string{courses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonsTable,
			Columns: []string{courses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.QuizzesTable,
			Columns: []string{courses.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuizzesIDs(); len(nodes) > 0 && !_u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.QuizzesTable,
			Columns: []string{courses.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.QuizzesTable,
			Columns: []string{courses.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.EnrollmentsTable,
			Columns: []string{courses.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollments.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnrollmentsIDs(); len(nodes) > 0 && !_u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.EnrollmentsTable,
			Columns: []string{courses.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollments.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.EnrollmentsTable,
			Columns: []string{courses.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollments.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonProgressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonProgressesTable,
			Columns: []string{courses.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLessonProgressesIDs(); len(nodes) > 0 && !_u.mutation.LessonProgressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonProgressesTable,
			Columns: []string{courses.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonProgressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonProgressesTable,
			Columns: []string{courses.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CertificatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.CertificatesTable,
			Columns: []string{courses.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificates.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCertificatesIDs(); len(nodes) > 0 && !_u.mutation.CertificatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.CertificatesTable,
			Columns: []string{courses.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificates.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CertificatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.CertificatesTable,
			Columns: []string{courses.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificates.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{courses.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CoursesUpdateOne is the builder for updating a single Courses entity.
type CoursesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CoursesMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoursesUpdateOne) SetDeletedAt(v time.Time) *CoursesUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillableDeletedAt(v *time.Time) *CoursesUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoursesUpdateOne) ClearDeletedAt() *CoursesUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *CoursesUpdateOne) SetCategoryID(v int) *CoursesUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillableCategoryID(v *int) *CoursesUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *CoursesUpdateOne) SetTitle(v string) *CoursesUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillableTitle(v *string) *CoursesUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *CoursesUpdateOne) SetSlug(v string) *CoursesUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillableSlug(v *string) *CoursesUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CoursesUpdateOne) SetDescription(v string) *CoursesUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillableDescription(v *string) *CoursesUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CoursesUpdateOne) ClearDescription() *CoursesUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetThumbnail sets the "thumbnail" field.
func (_u *CoursesUpdateOne) SetThumbnail(v string) *CoursesUpdateOne {
	_u.mutation.SetThumbnail(v)
	return _u
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillableThumbnail(v *string) *CoursesUpdateOne {
	if v != nil {
		_u.SetThumbnail(*v)
	}
	return _u
}

// ClearThumbnail clears the value of the "thumbnail" field.
func (_u *CoursesUpdateOne) ClearThumbnail() *CoursesUpdateOne {
	_u.mutation.ClearThumbnail()
	return _u
}

// SetPrice sets the "price" field.
func (_u *CoursesUpdateOne) SetPrice(v float64) *CoursesUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillablePrice(v *float64) *CoursesUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *CoursesUpdateOne) AddPrice(v float64) *CoursesUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetLevel sets the "level" field.
func (_u *CoursesUpdateOne) SetLevel(v courses.Level) *CoursesUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillableLevel(v *courses.Level) *CoursesUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CoursesUpdateOne) SetStatus(v courses.Status) *CoursesUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillableStatus(v *courses.Status) *CoursesUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalLessons sets the "total_lessons" field.
func (_u *CoursesUpdateOne) SetTotalLessons(v int) *CoursesUpdateOne {
	_u.mutation.ResetTotalLessons()
	_u.mutation.SetTotalLessons(v)
	return _u
}

// SetNillableTotalLessons sets the "total_lessons" field if the given value is not nil.
func (_u *CoursesUpdateOne) SetNillableTotalLessons(v *int) *CoursesUpdateOne {
	if v != nil {
		_u.SetTotalLessons(*v)
	}
	return _u
}

// AddTotalLessons adds value to the "total_lessons" field.
func (_u *CoursesUpdateOne) AddTotalLessons(v int) *CoursesUpdateOne {
	_u.mutation.AddTotalLessons(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoursesUpdateOne) SetUpdatedAt(v time.Time) *CoursesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCategoriesID sets the "Categories" edge to the Categories entity by ID.
func (_u *CoursesUpdateOne) SetCategoriesID(id int) *CoursesUpdateOne {
	_u.mutation.SetCategoriesID(id)
	return _u
}

// SetCategories sets the "Categories" edge to the Categories entity.
func (_u *CoursesUpdateOne) SetCategories(v *Categories) *CoursesUpdateOne {
	return _u.SetCategoriesID(v.ID)
}

// AddSectionIDs adds the "Sections" edge to the Sections entity by IDs.
func (_u *CoursesUpdateOne) AddSectionIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.AddSectionIDs(ids...)
	return _u
}

// AddSections adds the "Sections" edges to the Sections entity.
func (_u *CoursesUpdateOne) AddSections(v ...*Sections) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSectionIDs(ids...)
}

// AddLessonIDs adds the "Lessons" edge to the Lessons entity by IDs.
func (_u *CoursesUpdateOne) AddLessonIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.AddLessonIDs(ids...)
	return _u
}

// AddLessons adds the "Lessons" edges to the Lessons entity.
func (_u *CoursesUpdateOne) AddLessons(v ...*Lessons) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLessonIDs(ids...)
}

// AddQuizzeIDs adds the "Quizzes" edge to the Quizzes entity by IDs.
func (_u *CoursesUpdateOne) AddQuizzeIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.AddQuizzeIDs(ids...)
	return _u
}

// AddQuizzes adds the "Quizzes" edges to the Quizzes entity.
func (_u *CoursesUpdateOne) AddQuizzes(v ...*Quizzes) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuizzeIDs(ids...)
}

// AddEnrollmentIDs adds the "Enrollments" edge to the Enrollments entity by IDs.
func (_u *CoursesUpdateOne) AddEnrollmentIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.AddEnrollmentIDs(ids...)
	return _u
}

// AddEnrollments adds the "Enrollments" edges to the Enrollments entity.
func (_u *CoursesUpdateOne) AddEnrollments(v ...*Enrollments) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnrollmentIDs(ids...)
}

// AddLessonProgressIDs adds the "LessonProgresses" edge to the LessonProgresses entity by IDs.
func (_u *CoursesUpdateOne) AddLessonProgressIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.AddLessonProgressIDs(ids...)
	return _u
}

// AddLessonProgresses adds the "LessonProgresses" edges to the LessonProgresses entity.
func (_u *CoursesUpdateOne) AddLessonProgresses(v ...*LessonProgresses) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLessonProgressIDs(ids...)
}

// AddCertificateIDs adds the "Certificates" edge to the Certificates entity by IDs.
func (_u *CoursesUpdateOne) AddCertificateIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.AddCertificateIDs(ids...)
	return _u
}

// AddCertificates adds the "Certificates" edges to the Certificates entity.
func (_u *CoursesUpdateOne) AddCertificates(v ...*Certificates) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCertificateIDs(ids...)
}

// Mutation returns the CoursesMutation object of the builder.
func (_u *CoursesUpdateOne) Mutation() *CoursesMutation {
	return _u.mutation
}

// ClearCategories clears the "Categories" edge to the Categories entity.
func (_u *CoursesUpdateOne) ClearCategories() *CoursesUpdateOne {
	_u.mutation.ClearCategories()
	return _u
}

// ClearSections clears all "Sections" edges to the Sections entity.
func (_u *CoursesUpdateOne) ClearSections() *CoursesUpdateOne {
	_u.mutation.ClearSections()
	return _u
}

// RemoveSectionIDs removes the "Sections" edge to Sections entities by IDs.
func (_u *CoursesUpdateOne) RemoveSectionIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.RemoveSectionIDs(ids...)
	return _u
}

// RemoveSections removes "Sections" edges to Sections entities.
func (_u *CoursesUpdateOne) RemoveSections(v ...*Sections) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSectionIDs(ids...)
}

// ClearLessons clears all "Lessons" edges to the Lessons entity.
func (_u *CoursesUpdateOne) ClearLessons() *CoursesUpdateOne {
	_u.mutation.ClearLessons()
	return _u
}

// RemoveLessonIDs removes the "Lessons" edge to Lessons entities by IDs.
func (_u *CoursesUpdateOne) RemoveLessonIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.RemoveLessonIDs(ids...)
	return _u
}

// RemoveLessons removes "Lessons" edges to Lessons entities.
func (_u *CoursesUpdateOne) RemoveLessons(v ...*Lessons) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLessonIDs(ids...)
}

// ClearQuizzes clears all "Quizzes" edges to the Quizzes entity.
func (_u *CoursesUpdateOne) ClearQuizzes() *CoursesUpdateOne {
	_u.mutation.ClearQuizzes()
	return _u
}

// RemoveQuizzeIDs removes the "Quizzes" edge to Quizzes entities by IDs.
func (_u *CoursesUpdateOne) RemoveQuizzeIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.RemoveQuizzeIDs(ids...)
	return _u
}

// RemoveQuizzes removes "Quizzes" edges to Quizzes entities.
func (_u *CoursesUpdateOne) RemoveQuizzes(v ...*Quizzes) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuizzeIDs(ids...)
}

// ClearEnrollments clears all "Enrollments" edges to the Enrollments entity.
func (_u *CoursesUpdateOne) ClearEnrollments() *CoursesUpdateOne {
	_u.mutation.ClearEnrollments()
	return _u
}

// RemoveEnrollmentIDs removes the "Enrollments" edge to Enrollments entities by IDs.
func (_u *CoursesUpdateOne) RemoveEnrollmentIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.RemoveEnrollmentIDs(ids...)
	return _u
}

// RemoveEnrollments removes "Enrollments" edges to Enrollments entities.
func (_u *CoursesUpdateOne) RemoveEnrollments(v ...*Enrollments) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnrollmentIDs(ids...)
}

// ClearLessonProgresses clears all "LessonProgresses" edges to the LessonProgresses entity.
func (_u *CoursesUpdateOne) ClearLessonProgresses() *CoursesUpdateOne {
	_u.mutation.ClearLessonProgresses()
	return _u
}

// RemoveLessonProgressIDs removes the "LessonProgresses" edge to LessonProgresses entities by IDs.
func (_u *CoursesUpdateOne) RemoveLessonProgressIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.RemoveLessonProgressIDs(ids...)
	return _u
}

// RemoveLessonProgresses removes "LessonProgresses" edges to LessonProgresses entities.
func (_u *CoursesUpdateOne) RemoveLessonProgresses(v ...*LessonProgresses) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLessonProgressIDs(ids...)
}

// ClearCertificates clears all "Certificates" edges to the Certificates entity.
func (_u *CoursesUpdateOne) ClearCertificates() *CoursesUpdateOne {
	_u.mutation.ClearCertificates()
	return _u
}

// RemoveCertificateIDs removes the "Certificates" edge to Certificates entities by IDs.
func (_u *CoursesUpdateOne) RemoveCertificateIDs(ids ...int) *CoursesUpdateOne {
	_u.mutation.RemoveCertificateIDs(ids...)
	return _u
}

// RemoveCertificates removes "Certificates" edges to Certificates entities.
func (_u *CoursesUpdateOne) RemoveCertificates(v ...*Certificates) *CoursesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCertificateIDs(ids...)
}

// Where appends a list predicates to the CoursesUpdate builder.
func (_u *CoursesUpdateOne) Where(ps ...predicate.Courses) *CoursesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CoursesUpdateOne) Select(field string, fields ...string) *CoursesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Courses entity.
func (_u *CoursesUpdateOne) Save(ctx context.Context) (*Courses, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoursesUpdateOne) SaveX(ctx context.Context) *Courses {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CoursesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoursesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoursesUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if courses.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized courses.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := courses.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CoursesUpdateOne) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := courses.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Courses.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := courses.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Courses.status": %w`, err)}
		}
	}
	if _u.mutation.CategoriesCleared() && len(_u.mutation.CategoriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Courses.Categories"`)
	}
	return nil
}

func (_u *CoursesUpdateOne) sqlSave(ctx context.Context) (_node *Courses, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(courses.Table, courses.Columns, sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Courses.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, courses.FieldID)
		for _, f := range fields {
			if !courses.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != courses.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(courses.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(courses.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(courses.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(courses.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(courses.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(courses.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Thumbnail(); ok {
		_spec.SetField(courses.FieldThumbnail, field.TypeString, value)
	}
	if _u.mutation.ThumbnailCleared() {
		_spec.ClearField(courses.FieldThumbnail, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(courses.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(courses.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(courses.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(courses.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TotalLessons(); ok {
		_spec.SetField(courses.FieldTotalLessons, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalLessons(); ok {
		_spec.AddField(courses.FieldTotalLessons, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(courses.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   courses.CategoriesTable,
			Columns: []string{courses.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   courses.CategoriesTable,
			Columns: []string{courses.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.SectionsTable,
			Columns: []string{courses.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSectionsIDs(); len(nodes) > 0 && !_u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.SectionsTable,
			Columns: []string{courses.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.SectionsTable,
			Columns: []string{courses.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonsTable,
			Columns: []string{courses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLessonsIDs(); len(nodes) > 0 && !_u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonsTable,
			Columns: []string{courses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonsTable,
			Columns: []string{courses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.QuizzesTable,
			Columns: []string{courses.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuizzesIDs(); len(nodes) > 0 && !_u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.QuizzesTable,
			Columns: []string{courses.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.QuizzesTable,
			Columns: []string{courses.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.EnrollmentsTable,
			Columns: []string{courses.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollments.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnrollmentsIDs(); len(nodes) > 0 && !_u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.EnrollmentsTable,
			Columns: []string{courses.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollments.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.EnrollmentsTable,
			Columns: []string{courses.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollments.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonProgressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonProgressesTable,
			Columns: []string{courses.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLessonProgressesIDs(); len(nodes) > 0 && !_u.mutation.LessonProgressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonProgressesTable,
			Columns: []string{courses.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonProgressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.LessonProgressesTable,
			Columns: []string{courses.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CertificatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.CertificatesTable,
			Columns: []string{courses.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificates.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCertificatesIDs(); len(nodes) > 0 && !_u.mutation.CertificatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.CertificatesTable,
			Columns: []string{courses.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificates.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CertificatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courses.CertificatesTable,
			Columns: []string{courses.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificates.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Courses{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{courses.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
