// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-api/ent/courses"
	"lms-api/ent/lessonprogresses"
	"lms-api/ent/lessons"
	"lms-api/ent/users"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LessonProgressesCreate is the builder for creating a LessonProgresses entity.
type LessonProgressesCreate struct {
	config
	mutation *LessonProgressesMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *LessonProgressesCreate) SetUserID(v int) *LessonProgressesCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCourseID sets the "course_id" field.
func (_c *LessonProgressesCreate) SetCourseID(v int) *LessonProgressesCreate {
	_c.mutation.SetCourseID(v)
	return _c
}

// SetLessonID sets the "lesson_id" field.
func (_c *LessonProgressesCreate) SetLessonID(v int) *LessonProgressesCreate {
	_c.mutation.SetLessonID(v)
	return _c
}

// SetIsCompleted sets the "is_completed" field.
func (_c *LessonProgressesCreate) SetIsCompleted(v bool) *LessonProgressesCreate {
	_c.mutation.SetIsCompleted(v)
	return _c
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_c *LessonProgressesCreate) SetNillableIsCompleted(v *bool) *LessonProgressesCreate {
	if v != nil {
		_c.SetIsCompleted(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *LessonProgressesCreate) SetCompletedAt(v time.Time) *LessonProgressesCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *LessonProgressesCreate) SetNillableCompletedAt(v *time.Time) *LessonProgressesCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LessonProgressesCreate) SetCreatedAt(v time.Time) *LessonProgressesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LessonProgressesCreate) SetNillableCreatedAt(v *time.Time) *LessonProgressesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LessonProgressesCreate) SetUpdatedAt(v time.Time) *LessonProgressesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LessonProgressesCreate) SetNillableUpdatedAt(v *time.Time) *LessonProgressesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_c *LessonProgressesCreate) SetUsersID(id int) *LessonProgressesCreate {
	_c.mutation.SetUsersID(id)
	return _c
}

// SetUsers sets the "Users" edge to the Users entity.
func (_c *LessonProgressesCreate) SetUsers(v *Users) *LessonProgressesCreate {
	return _c.SetUsersID(v.ID)
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_c *LessonProgressesCreate) SetCoursesID(id int) *LessonProgressesCreate {
	_c.mutation.SetCoursesID(id)
	return _c
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_c *LessonProgressesCreate) SetCourses(v *Courses) *LessonProgressesCreate {
	return _c.SetCoursesID(v.ID)
}

// SetLessonsID sets the "Lessons" edge to the Lessons entity by ID.
func (_c *LessonProgressesCreate) SetLessonsID(id int) *LessonProgressesCreate {
	_c.mutation.SetLessonsID(id)
	return _c
}

// SetLessons sets the "Lessons" edge to the Lessons entity.
func (_c *LessonProgressesCreate) SetLessons(v *Lessons) *LessonProgressesCreate {
	return _c.SetLessonsID(v.ID)
}

// Mutation returns the LessonProgressesMutation object of the builder.
func (_c *LessonProgressesCreate) Mutation() *LessonProgressesMutation {
	return _c.mutation
}

// Save creates the LessonProgresses in the database.
func (_c *LessonProgressesCreate) Save(ctx context.Context) (*LessonProgresses, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LessonProgressesCreate) SaveX(ctx context.Context) *LessonProgresses {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LessonProgressesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LessonProgressesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LessonProgressesCreate) defaults() {
	if _, ok := _c.mutation.IsCompleted(); !ok {
		v := lessonprogresses.DefaultIsCompleted
		_c.mutation.SetIsCompleted(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lessonprogresses.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lessonprogresses.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LessonProgressesCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LessonProgresses.user_id"`)}
	}
	if _, ok := _c.mutation.CourseID(); !ok {
		return &ValidationError{Name: "course_id", err: errors.New(`ent: missing required field "LessonProgresses.course_id"`)}
	}
	if _, ok := _c.mutation.LessonID(); !ok {
		return &ValidationError{Name: "lesson_id", err: errors.New(`ent: missing required field "LessonProgresses.lesson_id"`)}
	}
	if _, ok := _c.mutation.IsCompleted(); !ok {
		return &ValidationError{Name: "is_completed", err: errors.New(`ent: missing required field "LessonProgresses.is_completed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LessonProgresses.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LessonProgresses.updated_at"`)}
	}
	if len(_c.mutation.UsersIDs()) == 0 {
		return &ValidationError{Name: "Users", err: errors.New(`ent: missing required edge "LessonProgresses.Users"`)}
	}
	if len(_c.mutation.CoursesIDs()) == 0 {
		return &ValidationError{Name: "Courses", err: errors.New(`ent: missing required edge "LessonProgresses.Courses"`)}
	}
	if len(_c.mutation.LessonsIDs()) == 0 {
		return &ValidationError{Name: "Lessons", err: errors.New(`ent: missing required edge "LessonProgresses.Lessons"`)}
	}
	return nil
}

func (_c *LessonProgressesCreate) sqlSave(ctx context.Context) (*LessonProgresses, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LessonProgressesCreate) createSpec() (*LessonProgresses, *sqlgraph.CreateSpec) {
	var (
		_node = &LessonProgresses{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lessonprogresses.Table, sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.IsCompleted(); ok {
		_spec.SetField(lessonprogresses.FieldIsCompleted, field.TypeBool, value)
		_node.IsCompleted = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(lessonprogresses.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lessonprogresses.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lessonprogresses.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.UsersTable,
			Columns: []string{lessonprogresses.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.CoursesTable,
			Columns: []string{lessonprogresses.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CourseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.LessonsTable,
			Columns: []string{lessonprogresses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LessonID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LessonProgressesCreateBulk is the builder for creating many LessonProgresses entities in bulk.
type LessonProgressesCreateBulk struct {
	config
	err      error
	builders []*LessonProgressesCreate
}

// Save creates the LessonProgresses entities in the database.
func (_c *LessonProgressesCreateBulk) Save(ctx context.Context) ([]*LessonProgresses, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LessonProgresses, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LessonProgressesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LessonProgressesCreateBulk) SaveX(ctx context.Context) []*LessonProgresses {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LessonProgressesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LessonProgressesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
