// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-api/ent/predicate"
	"lms-api/ent/quizattempts"
	"lms-api/ent/quizzes"
	"lms-api/ent/users"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizAttemptsUpdate is the builder for updating QuizAttempts entities.
type QuizAttemptsUpdate struct {
	config
	hooks    []Hook
	mutation *QuizAttemptsMutation
}

// Where appends a list predicates to the QuizAttemptsUpdate builder.
func (_u *QuizAttemptsUpdate) Where(ps ...predicate.QuizAttempts) *QuizAttemptsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *QuizAttemptsUpdate) SetUserID(v int) *QuizAttemptsUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QuizAttemptsUpdate) SetNillableUserID(v *int) *QuizAttemptsUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetQuizID sets the "quiz_id" field.
func (_u *QuizAttemptsUpdate) SetQuizID(v int) *QuizAttemptsUpdate {
	_u.mutation.SetQuizID(v)
	return _u
}

// SetNillableQuizID sets the "quiz_id" field if the given value is not nil.
func (_u *QuizAttemptsUpdate) SetNillableQuizID(v *int) *QuizAttemptsUpdate {
	if v != nil {
		_u.SetQuizID(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *QuizAttemptsUpdate) SetScore(v float64) *QuizAttemptsUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *QuizAttemptsUpdate) SetNillableScore(v *float64) *QuizAttemptsUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *QuizAttemptsUpdate) AddScore(v float64) *QuizAttemptsUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetTotalQuestions sets the "total_questions" field.
func (_u *QuizAttemptsUpdate) SetTotalQuestions(v int) *QuizAttemptsUpdate {
	_u.mutation.ResetTotalQuestions()
	_u.mutation.SetTotalQuestions(v)
	return _u
}

// SetNillableTotalQuestions sets the "total_questions" field if the given value is not nil.
func (_u *QuizAttemptsUpdate) SetNillableTotalQuestions(v *int) *QuizAttemptsUpdate {
	if v != nil {
		_u.SetTotalQuestions(*v)
	}
	return _u
}

// AddTotalQuestions adds value to the "total_questions" field.
func (_u *QuizAttemptsUpdate) AddTotalQuestions(v int) *QuizAttemptsUpdate {
	_u.mutation.AddTotalQuestions(v)
	return _u
}

// SetCorrectAnswers sets the "correct_answers" field.
func (_u *QuizAttemptsUpdate) SetCorrectAnswers(v int) *QuizAttemptsUpdate {
	_u.mutation.ResetCorrectAnswers()
	_u.mutation.SetCorrectAnswers(v)
	return _u
}

// SetNillableCorrectAnswers sets the "correct_answers" field if the given value is not nil.
func (_u *QuizAttemptsUpdate) SetNillableCorrectAnswers(v *int) *QuizAttemptsUpdate {
	if v != nil {
		_u.SetCorrectAnswers(*v)
	}
	return _u
}

// AddCorrectAnswers adds value to the "correct_answers" field.
func (_u *QuizAttemptsUpdate) AddCorrectAnswers(v int) *QuizAttemptsUpdate {
	_u.mutation.AddCorrectAnswers(v)
	return _u
}

// SetIsPassed sets the "is_passed" field.
func (_u *QuizAttemptsUpdate) SetIsPassed(v bool) *QuizAttemptsUpdate {
	_u.mutation.SetIsPassed(v)
	return _u
}

// SetNillableIsPassed sets the "is_passed" field if the given value is not nil.
func (_u *QuizAttemptsUpdate) SetNillableIsPassed(v *bool) *QuizAttemptsUpdate {
	if v != nil {
		_u.SetIsPassed(*v)
	}
	return _u
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *QuizAttemptsUpdate) SetUsersID(id int) *QuizAttemptsUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *QuizAttemptsUpdate) SetUsers(v *Users) *QuizAttemptsUpdate {
	return _u.SetUsersID(v.ID)
}

// SetQuizzesID sets the "Quizzes" edge to the Quizzes entity by ID.
func (_u *QuizAttemptsUpdate) SetQuizzesID(id int) *QuizAttemptsUpdate {
	_u.mutation.SetQuizzesID(id)
	return _u
}

// SetQuizzes sets the "Quizzes" edge to the Quizzes entity.
func (_u *QuizAttemptsUpdate) SetQuizzes(v *Quizzes) *QuizAttemptsUpdate {
	return _u.SetQuizzesID(v.ID)
}

// Mutation returns the QuizAttemptsMutation object of the builder.
func (_u *QuizAttemptsUpdate) Mutation() *QuizAttemptsMutation {
	return _u.mutation
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *QuizAttemptsUpdate) ClearUsers() *QuizAttemptsUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// ClearQuizzes clears the "Quizzes" edge to the Quizzes entity.
func (_u *QuizAttemptsUpdate) ClearQuizzes() *QuizAttemptsUpdate {
	_u.mutation.ClearQuizzes()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuizAttemptsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizAttemptsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuizAttemptsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizAttemptsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizAttemptsUpdate) check() error {
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuizAttempts.Users"`)
	}
	if _u.mutation.QuizzesCleared() && len(_u.mutation.QuizzesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuizAttempts.Quizzes"`)
	}
	return nil
}

func (_u *QuizAttemptsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quizattempts.Table, quizattempts.Columns, sqlgraph.NewFieldSpec(quizattempts.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(quizattempts.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(quizattempts.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalQuestions(); ok {
		_spec.SetField(quizattempts.FieldTotalQuestions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalQuestions(); ok {
		_spec.AddField(quizattempts.FieldTotalQuestions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CorrectAnswers(); ok {
		_spec.SetField(quizattempts.FieldCorrectAnswers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCorrectAnswers(); ok {
		_spec.AddField(quizattempts.FieldCorrectAnswers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPassed(); ok {
		_spec.SetField(quizattempts.FieldIsPassed, field.TypeBool, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizattempts.UsersTable,
			Columns: []string{quizattempts.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizattempts.UsersTable,
			Columns: []string{quizattempts.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizattempts.QuizzesTable,
			Columns: []string{quizattempts.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizattempts.QuizzesTable,
			Columns: []string{quizattempts.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quizattempts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuizAttemptsUpdateOne is the builder for updating a single QuizAttempts entity.
type QuizAttemptsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuizAttemptsMutation
}

// SetUserID sets the "user_id" field.
func (_u *QuizAttemptsUpdateOne) SetUserID(v int) *QuizAttemptsUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QuizAttemptsUpdateOne) SetNillableUserID(v *int) *QuizAttemptsUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetQuizID sets the "quiz_id" field.
func (_u *QuizAttemptsUpdateOne) SetQuizID(v int) *QuizAttemptsUpdateOne {
	_u.mutation.SetQuizID(v)
	return _u
}

// SetNillableQuizID sets the "quiz_id" field if the given value is not nil.
func (_u *QuizAttemptsUpdateOne) SetNillableQuizID(v *int) *QuizAttemptsUpdateOne {
	if v != nil {
		_u.SetQuizID(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *QuizAttemptsUpdateOne) SetScore(v float64) *QuizAttemptsUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *QuizAttemptsUpdateOne) SetNillableScore(v *float64) *QuizAttemptsUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *QuizAttemptsUpdateOne) AddScore(v float64) *QuizAttemptsUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetTotalQuestions sets the "total_questions" field.
func (_u *QuizAttemptsUpdateOne) SetTotalQuestions(v int) *QuizAttemptsUpdateOne {
	_u.mutation.ResetTotalQuestions()
	_u.mutation.SetTotalQuestions(v)
	return _u
}

// SetNillableTotalQuestions sets the "total_questions" field if the given value is not nil.
func (_u *QuizAttemptsUpdateOne) SetNillableTotalQuestions(v *int) *QuizAttemptsUpdateOne {
	if v != nil {
		_u.SetTotalQuestions(*v)
	}
	return _u
}

// AddTotalQuestions adds value to the "total_questions" field.
func (_u *QuizAttemptsUpdateOne) AddTotalQuestions(v int) *QuizAttemptsUpdateOne {
	_u.mutation.AddTotalQuestions(v)
	return _u
}

// SetCorrectAnswers sets the "correct_answers" field.
func (_u *QuizAttemptsUpdateOne) SetCorrectAnswers(v int) *QuizAttemptsUpdateOne {
	_u.mutation.ResetCorrectAnswers()
	_u.mutation.SetCorrectAnswers(v)
	return _u
}

// SetNillableCorrectAnswers sets the "correct_answers" field if the given value is not nil.
func (_u *QuizAttemptsUpdateOne) SetNillableCorrectAnswers(v *int) *QuizAttemptsUpdateOne {
	if v != nil {
		_u.SetCorrectAnswers(*v)
	}
	return _u
}

// AddCorrectAnswers adds value to the "correct_answers" field.
func (_u *QuizAttemptsUpdateOne) AddCorrectAnswers(v int) *QuizAttemptsUpdateOne {
	_u.mutation.AddCorrectAnswers(v)
	return _u
}

// SetIsPassed sets the "is_passed" field.
func (_u *QuizAttemptsUpdateOne) SetIsPassed(v bool) *QuizAttemptsUpdateOne {
	_u.mutation.SetIsPassed(v)
	return _u
}

// SetNillableIsPassed sets the "is_passed" field if the given value is not nil.
func (_u *QuizAttemptsUpdateOne) SetNillableIsPassed(v *bool) *QuizAttemptsUpdateOne {
	if v != nil {
		_u.SetIsPassed(*v)
	}
	return _u
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *QuizAttemptsUpdateOne) SetUsersID(id int) *QuizAttemptsUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *QuizAttemptsUpdateOne) SetUsers(v *Users) *QuizAttemptsUpdateOne {
	return _u.SetUsersID(v.ID)
}

// SetQuizzesID sets the "Quizzes" edge to the Quizzes entity by ID.
func (_u *QuizAttemptsUpdateOne) SetQuizzesID(id int) *QuizAttemptsUpdateOne {
	_u.mutation.SetQuizzesID(id)
	return _u
}

// SetQuizzes sets the "Quizzes" edge to the Quizzes entity.
func (_u *QuizAttemptsUpdateOne) SetQuizzes(v *Quizzes) *QuizAttemptsUpdateOne {
	return _u.SetQuizzesID(v.ID)
}

// Mutation returns the QuizAttemptsMutation object of the builder.
func (_u *QuizAttemptsUpdateOne) Mutation() *QuizAttemptsMutation {
	return _u.mutation
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *QuizAttemptsUpdateOne) ClearUsers() *QuizAttemptsUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// ClearQuizzes clears the "Quizzes" edge to the Quizzes entity.
func (_u *QuizAttemptsUpdateOne) ClearQuizzes() *QuizAttemptsUpdateOne {
	_u.mutation.ClearQuizzes()
	return _u
}

// Where appends a list predicates to the QuizAttemptsUpdate builder.
func (_u *QuizAttemptsUpdateOne) Where(ps ...predicate.QuizAttempts) *QuizAttemptsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuizAttemptsUpdateOne) Select(field string, fields ...string) *QuizAttemptsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuizAttempts entity.
func (_u *QuizAttemptsUpdateOne) Save(ctx context.Context) (*QuizAttempts, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizAttemptsUpdateOne) SaveX(ctx context.Context) *QuizAttempts {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuizAttemptsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizAttemptsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizAttemptsUpdateOne) check() error {
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuizAttempts.Users"`)
	}
	if _u.mutation.QuizzesCleared() && len(_u.mutation.QuizzesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuizAttempts.Quizzes"`)
	}
	return nil
}

func (_u *QuizAttemptsUpdateOne) sqlSave(ctx context.Context) (_node *QuizAttempts, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quizattempts.Table, quizattempts.Columns, sqlgraph.NewFieldSpec(quizattempts.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuizAttempts.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quizattempts.FieldID)
		for _, f := range fields {
			if !quizattempts.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quizattempts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(quizattempts.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(quizattempts.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalQuestions(); ok {
		_spec.SetField(quizattempts.FieldTotalQuestions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalQuestions(); ok {
		_spec.AddField(quizattempts.FieldTotalQuestions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CorrectAnswers(); ok {
		_spec.SetField(quizattempts.FieldCorrectAnswers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCorrectAnswers(); ok {
		_spec.AddField(quizattempts.FieldCorrectAnswers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPassed(); ok {
		_spec.SetField(quizattempts.FieldIsPassed, field.TypeBool, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizattempts.UsersTable,
			Columns: []string{quizattempts.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizattempts.UsersTable,
			Columns: []string{quizattempts.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizattempts.QuizzesTable,
			Columns: []string{quizattempts.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizattempts.QuizzesTable,
			Columns: []string{quizattempts.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &QuizAttempts{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quizattempts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
