// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-api/ent/courses"
	"lms-api/ent/lessons"
	"lms-api/ent/predicate"
	"lms-api/ent/questions"
	"lms-api/ent/quizattempts"
	"lms-api/ent/quizzes"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizzesUpdate is the builder for updating Quizzes entities.
type QuizzesUpdate struct {
	config
	hooks    []Hook
	mutation *QuizzesMutation
}

// Where appends a list predicates to the QuizzesUpdate builder.
func (_u *QuizzesUpdate) Where(ps ...predicate.Quizzes) *QuizzesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *QuizzesUpdate) SetDeletedAt(v time.Time) *QuizzesUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *QuizzesUpdate) SetNillableDeletedAt(v *time.Time) *QuizzesUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *QuizzesUpdate) ClearDeletedAt() *QuizzesUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *QuizzesUpdate) SetCourseID(v int) *QuizzesUpdate {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *QuizzesUpdate) SetNillableCourseID(v *int) *QuizzesUpdate {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetLessonID sets the "lesson_id" field.
func (_u *QuizzesUpdate) SetLessonID(v int) *QuizzesUpdate {
	_u.mutation.SetLessonID(v)
	return _u
}

// SetNillableLessonID sets the "lesson_id" field if the given value is not nil.
func (_u *QuizzesUpdate) SetNillableLessonID(v *int) *QuizzesUpdate {
	if v != nil {
		_u.SetLessonID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *QuizzesUpdate) SetTitle(v string) *QuizzesUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *QuizzesUpdate) SetNillableTitle(v *string) *QuizzesUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPassingScore sets the "passing_score" field.
func (_u *QuizzesUpdate) SetPassingScore(v int) *QuizzesUpdate {
	_u.mutation.ResetPassingScore()
	_u.mutation.SetPassingScore(v)
	return _u
}

// SetNillablePassingScore sets the "passing_score" field if the given value is not nil.
func (_u *QuizzesUpdate) SetNillablePassingScore(v *int) *QuizzesUpdate {
	if v != nil {
		_u.SetPassingScore(*v)
	}
	return _u
}

// AddPassingScore adds value to the "passing_score" field.
func (_u *QuizzesUpdate) AddPassingScore(v int) *QuizzesUpdate {
	_u.mutation.AddPassingScore(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuizzesUpdate) SetUpdatedAt(v time.Time) *QuizzesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *QuizzesUpdate) SetCoursesID(id int) *QuizzesUpdate {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *QuizzesUpdate) SetCourses(v *Courses) *QuizzesUpdate {
	return _u.SetCoursesID(v.ID)
}

// SetLessonsID sets the "Lessons" edge to the Lessons entity by ID.
func (_u *QuizzesUpdate) SetLessonsID(id int) *QuizzesUpdate {
	_u.mutation.SetLessonsID(id)
	return _u
}

// SetLessons sets the "Lessons" edge to the Lessons entity.
func (_u *QuizzesUpdate) SetLessons(v *Lessons) *QuizzesUpdate {
	return _u.SetLessonsID(v.ID)
}

// AddQuestionIDs adds the "Questions" edge to the Questions entity by IDs.
func (_u *QuizzesUpdate) AddQuestionIDs(ids ...int) *QuizzesUpdate {
	_u.mutation.AddQuestionIDs(ids...)
	return _u
}

// AddQuestions adds the "Questions" edges to the Questions entity.
func (_u *QuizzesUpdate) AddQuestions(v ...*Questions) *QuizzesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestionIDs(ids...)
}

// AddQuizAttemptIDs adds the "QuizAttempts" edge to the QuizAttempts entity by IDs.
func (_u *QuizzesUpdate) AddQuizAttemptIDs(ids ...int) *QuizzesUpdate {
	_u.mutation.AddQuizAttemptIDs(ids...)
	return _u
}

// AddQuizAttempts adds the "QuizAttempts" edges to the QuizAttempts entity.
func (_u *QuizzesUpdate) AddQuizAttempts(v ...*QuizAttempts) *QuizzesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuizAttemptIDs(ids...)
}

// Mutation returns the QuizzesMutation object of the builder.
func (_u *QuizzesUpdate) Mutation() *QuizzesMutation {
	return _u.mutation
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *QuizzesUpdate) ClearCourses() *QuizzesUpdate {
	_u.mutation.ClearCourses()
	return _u
}

// ClearLessons clears the "Lessons" edge to the Lessons entity.
func (_u *QuizzesUpdate) ClearLessons() *QuizzesUpdate {
	_u.mutation.ClearLessons()
	return _u
}

// ClearQuestions clears all "Questions" edges to the Questions entity.
func (_u *QuizzesUpdate) ClearQuestions() *QuizzesUpdate {
	_u.mutation.ClearQuestions()
	return _u
}

// RemoveQuestionIDs removes the "Questions" edge to Questions entities by IDs.
func (_u *QuizzesUpdate) RemoveQuestionIDs(ids ...int) *QuizzesUpdate {
	_u.mutation.RemoveQuestionIDs(ids...)
	return _u
}

// RemoveQuestions removes "Questions" edges to Questions entities.
func (_u *QuizzesUpdate) RemoveQuestions(v ...*Questions) *QuizzesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestionIDs(ids...)
}

// ClearQuizAttempts clears all "QuizAttempts" edges to the QuizAttempts entity.
func (_u *QuizzesUpdate) ClearQuizAttempts() *QuizzesUpdate {
	_u.mutation.ClearQuizAttempts()
	return _u
}

// RemoveQuizAttemptIDs removes the "QuizAttempts" edge to QuizAttempts entities by IDs.
func (_u *QuizzesUpdate) RemoveQuizAttemptIDs(ids ...int) *QuizzesUpdate {
	_u.mutation.RemoveQuizAttemptIDs(ids...)
	return _u
}

// RemoveQuizAttempts removes "QuizAttempts" edges to QuizAttempts entities.
func (_u *QuizzesUpdate) RemoveQuizAttempts(v ...*QuizAttempts) *QuizzesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuizAttemptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuizzesUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizzesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuizzesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizzesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuizzesUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if quizzes.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized quizzes.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := quizzes.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizzesUpdate) check() error {
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Quizzes.Courses"`)
	}
	if _u.mutation.LessonsCleared() && len(_u.mutation.LessonsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Quizzes.Lessons"`)
	}
	return nil
}

func (_u *QuizzesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quizzes.Table, quizzes.Columns, sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(quizzes.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(quizzes.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(quizzes.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassingScore(); ok {
		_spec.SetField(quizzes.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassingScore(); ok {
		_spec.AddField(quizzes.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quizzes.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizzes.CoursesTable,
			Columns: []string{quizzes.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizzes.CoursesTable,
			Columns: []string{quizzes.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizzes.LessonsTable,
			Columns: []string{quizzes.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizzes.LessonsTable,
			Columns: []string{quizzes.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuestionsTable,
			Columns: []string{quizzes.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestionsIDs(); len(nodes) > 0 && !_u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuestionsTable,
			Columns: []string{quizzes.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuestionsTable,
			Columns: []string{quizzes.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizAttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuizAttemptsTable,
			Columns: []string{quizzes.QuizAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizattempts.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuizAttemptsIDs(); len(nodes) > 0 && !_u.mutation.QuizAttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuizAttemptsTable,
			Columns: []string{quizzes.QuizAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizattempts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizAttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuizAttemptsTable,
			Columns: []string{quizzes.QuizAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizattempts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quizzes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuizzesUpdateOne is the builder for updating a single Quizzes entity.
type QuizzesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuizzesMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *QuizzesUpdateOne) SetDeletedAt(v time.Time) *QuizzesUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *QuizzesUpdateOne) SetNillableDeletedAt(v *time.Time) *QuizzesUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *QuizzesUpdateOne) ClearDeletedAt() *QuizzesUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *QuizzesUpdateOne) SetCourseID(v int) *QuizzesUpdateOne {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *QuizzesUpdateOne) SetNillableCourseID(v *int) *QuizzesUpdateOne {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetLessonID sets the "lesson_id" field.
func (_u *QuizzesUpdateOne) SetLessonID(v int) *QuizzesUpdateOne {
	_u.mutation.SetLessonID(v)
	return _u
}

// SetNillableLessonID sets the "lesson_id" field if the given value is not nil.
func (_u *QuizzesUpdateOne) SetNillableLessonID(v *int) *QuizzesUpdateOne {
	if v != nil {
		_u.SetLessonID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *QuizzesUpdateOne) SetTitle(v string) *QuizzesUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *QuizzesUpdateOne) SetNillableTitle(v *string) *QuizzesUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPassingScore sets the "passing_score" field.
func (_u *QuizzesUpdateOne) SetPassingScore(v int) *QuizzesUpdateOne {
	_u.mutation.ResetPassingScore()
	_u.mutation.SetPassingScore(v)
	return _u
}

// SetNillablePassingScore sets the "passing_score" field if the given value is not nil.
func (_u *QuizzesUpdateOne) SetNillablePassingScore(v *int) *QuizzesUpdateOne {
	if v != nil {
		_u.SetPassingScore(*v)
	}
	return _u
}

// AddPassingScore adds value to the "passing_score" field.
func (_u *QuizzesUpdateOne) AddPassingScore(v int) *QuizzesUpdateOne {
	_u.mutation.AddPassingScore(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuizzesUpdateOne) SetUpdatedAt(v time.Time) *QuizzesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *QuizzesUpdateOne) SetCoursesID(id int) *QuizzesUpdateOne {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *QuizzesUpdateOne) SetCourses(v *Courses) *QuizzesUpdateOne {
	return _u.SetCoursesID(v.ID)
}

// SetLessonsID sets the "Lessons" edge to the Lessons entity by ID.
func (_u *QuizzesUpdateOne) SetLessonsID(id int) *QuizzesUpdateOne {
	_u.mutation.SetLessonsID(id)
	return _u
}

// SetLessons sets the "Lessons" edge to the Lessons entity.
func (_u *QuizzesUpdateOne) SetLessons(v *Lessons) *QuizzesUpdateOne {
	return _u.SetLessonsID(v.ID)
}

// AddQuestionIDs adds the "Questions" edge to the Questions entity by IDs.
func (_u *QuizzesUpdateOne) AddQuestionIDs(ids ...int) *QuizzesUpdateOne {
	_u.mutation.AddQuestionIDs(ids...)
	return _u
}

// AddQuestions adds the "Questions" edges to the Questions entity.
func (_u *QuizzesUpdateOne) AddQuestions(v ...*Questions) *QuizzesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestionIDs(ids...)
}

// AddQuizAttemptIDs adds the "QuizAttempts" edge to the QuizAttempts entity by IDs.
func (_u *QuizzesUpdateOne) AddQuizAttemptIDs(ids ...int) *QuizzesUpdateOne {
	_u.mutation.AddQuizAttemptIDs(ids...)
	return _u
}

// AddQuizAttempts adds the "QuizAttempts" edges to the QuizAttempts entity.
func (_u *QuizzesUpdateOne) AddQuizAttempts(v ...*QuizAttempts) *QuizzesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuizAttemptIDs(ids...)
}

// Mutation returns the QuizzesMutation object of the builder.
func (_u *QuizzesUpdateOne) Mutation() *QuizzesMutation {
	return _u.mutation
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *QuizzesUpdateOne) ClearCourses() *QuizzesUpdateOne {
	_u.mutation.ClearCourses()
	return _u
}

// ClearLessons clears the "Lessons" edge to the Lessons entity.
func (_u *QuizzesUpdateOne) ClearLessons() *QuizzesUpdateOne {
	_u.mutation.ClearLessons()
	return _u
}

// ClearQuestions clears all "Questions" edges to the Questions entity.
func (_u *QuizzesUpdateOne) ClearQuestions() *QuizzesUpdateOne {
	_u.mutation.ClearQuestions()
	return _u
}

// RemoveQuestionIDs removes the "Questions" edge to Questions entities by IDs.
func (_u *QuizzesUpdateOne) RemoveQuestionIDs(ids ...int) *QuizzesUpdateOne {
	_u.mutation.RemoveQuestionIDs(ids...)
	return _u
}

// RemoveQuestions removes "Questions" edges to Questions entities.
func (_u *QuizzesUpdateOne) RemoveQuestions(v ...*Questions) *QuizzesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestionIDs(ids...)
}

// ClearQuizAttempts clears all "QuizAttempts" edges to the QuizAttempts entity.
func (_u *QuizzesUpdateOne) ClearQuizAttempts() *QuizzesUpdateOne {
	_u.mutation.ClearQuizAttempts()
	return _u
}

// RemoveQuizAttemptIDs removes the "QuizAttempts" edge to QuizAttempts entities by IDs.
func (_u *QuizzesUpdateOne) RemoveQuizAttemptIDs(ids ...int) *QuizzesUpdateOne {
	_u.mutation.RemoveQuizAttemptIDs(ids...)
	return _u
}

// RemoveQuizAttempts removes "QuizAttempts" edges to QuizAttempts entities.
func (_u *QuizzesUpdateOne) RemoveQuizAttempts(v ...*QuizAttempts) *QuizzesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuizAttemptIDs(ids...)
}

// Where appends a list predicates to the QuizzesUpdate builder.
func (_u *QuizzesUpdateOne) Where(ps ...predicate.Quizzes) *QuizzesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuizzesUpdateOne) Select(field string, fields ...string) *QuizzesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Quizzes entity.
func (_u *QuizzesUpdateOne) Save(ctx context.Context) (*Quizzes, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizzesUpdateOne) SaveX(ctx context.Context) *Quizzes {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuizzesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizzesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuizzesUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if quizzes.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized quizzes.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := quizzes.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizzesUpdateOne) check() error {
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Quizzes.Courses"`)
	}
	if _u.mutation.LessonsCleared() && len(_u.mutation.LessonsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Quizzes.Lessons"`)
	}
	return nil
}

func (_u *QuizzesUpdateOne) sqlSave(ctx context.Context) (_node *Quizzes, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quizzes.Table, quizzes.Columns, sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Quizzes.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quizzes.FieldID)
		for _, f := range fields {
			if !quizzes.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quizzes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(quizzes.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(quizzes.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(quizzes.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassingScore(); ok {
		_spec.SetField(quizzes.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassingScore(); ok {
		_spec.AddField(quizzes.FieldPassingScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quizzes.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizzes.CoursesTable,
			Columns: []string{quizzes.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizzes.CoursesTable,
			Columns: []string{quizzes.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizzes.LessonsTable,
			Columns: []string{quizzes.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizzes.LessonsTable,
			Columns: []string{quizzes.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuestionsTable,
			Columns: []string{quizzes.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestionsIDs(); len(nodes) > 0 && !_u.mutation.QuestionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuestionsTable,
			Columns: []string{quizzes.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuestionsTable,
			Columns: []string{quizzes.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizAttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuizAttemptsTable,
			Columns: []string{quizzes.QuizAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizattempts.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuizAttemptsIDs(); len(nodes) > 0 && !_u.mutation.QuizAttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuizAttemptsTable,
			Columns: []string{quizzes.QuizAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizattempts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizAttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizzes.QuizAttemptsTable,
			Columns: []string{quizzes.QuizAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizattempts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Quizzes{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quizzes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
