// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lms-api/ent/users"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Users is the model entity for the Users schema.
type Users struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deletedAt"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"-"`
	// FullName holds the value of the "full_name" field.
	FullName *string `json:"full_name,omitempty"`
	// Avatar holds the value of the "avatar" field.
	Avatar *string `json:"avatar,omitempty"`
	// Role holds the value of the "role" field.
	Role users.Role `json:"role,omitempty"`
	// Status holds the value of the "status" field.
	Status users.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsersQuery when eager-loading is set.
	Edges        UsersEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsersEdges holds the relations/edges for other nodes in the graph.
type UsersEdges struct {
	// Enrollments holds the value of the Enrollments edge.
	Enrollments []*Enrollments `json:"Enrollments,omitempty"`
	// LessonProgresses holds the value of the LessonProgresses edge.
	LessonProgresses []*LessonProgresses `json:"LessonProgresses,omitempty"`
	// QuizAttempts holds the value of the QuizAttempts edge.
	QuizAttempts []*QuizAttempts `json:"QuizAttempts,omitempty"`
	// Certificates holds the value of the Certificates edge.
	Certificates []*Certificates `json:"Certificates,omitempty"`
	// Notifications holds the value of the Notifications edge.
	Notifications []*Notifications `json:"Notifications,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// EnrollmentsOrErr returns the Enrollments value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) EnrollmentsOrErr() ([]*Enrollments, error) {
	if e.loadedTypes[0] {
		return e.Enrollments, nil
	}
	return nil, &NotLoadedError{edge: "Enrollments"}
}

// LessonProgressesOrErr returns the LessonProgresses value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) LessonProgressesOrErr() ([]*LessonProgresses, error) {
	if e.loadedTypes[1] {
		return e.LessonProgresses, nil
	}
	return nil, &NotLoadedError{edge: "LessonProgresses"}
}

// QuizAttemptsOrErr returns the QuizAttempts value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) QuizAttemptsOrErr() ([]*QuizAttempts, error) {
	if e.loadedTypes[2] {
		return e.QuizAttempts, nil
	}
	return nil, &NotLoadedError{edge: "QuizAttempts"}
}

// CertificatesOrErr returns the Certificates value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) CertificatesOrErr() ([]*Certificates, error) {
	if e.loadedTypes[3] {
		return e.Certificates, nil
	}
	return nil, &NotLoadedError{edge: "Certificates"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) NotificationsOrErr() ([]*Notifications, error) {
	if e.loadedTypes[4] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "Notifications"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Users) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case users.FieldID:
			values[i] = new(sql.NullInt64)
		case users.FieldEmail, users.FieldPassword, users.FieldFullName, users.FieldAvatar, users.FieldRole, users.FieldStatus:
			values[i] = new(sql.NullString)
		case users.FieldDeletedAt, users.FieldCreatedAt, users.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Users fields.
func (_m *Users) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case users.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case users.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case users.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case users.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case users.FieldFullName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_name", values[i])
			} else if value.Valid {
				_m.FullName = new(string)
				*_m.FullName = value.String
			}
		case users.FieldAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar", values[i])
			} else if value.Valid {
				_m.Avatar = new(string)
				*_m.Avatar = value.String
			}
		case users.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = users.Role(value.String)
			}
		case users.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = users.Status(value.String)
			}
		case users.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case users.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Users.
// This includes values selected through modifiers, order, etc.
func (_m *Users) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEnrollments queries the "Enrollments" edge of the Users entity.
func (_m *Users) QueryEnrollments() *EnrollmentsQuery {
	return NewUsersClient(_m.config).QueryEnrollments(_m)
}

// QueryLessonProgresses queries the "LessonProgresses" edge of the Users entity.
func (_m *Users) QueryLessonProgresses() *LessonProgressesQuery {
	return NewUsersClient(_m.config).QueryLessonProgresses(_m)
}

// QueryQuizAttempts queries the "QuizAttempts" edge of the Users entity.
func (_m *Users) QueryQuizAttempts() *QuizAttemptsQuery {
	return NewUsersClient(_m.config).QueryQuizAttempts(_m)
}

// QueryCertificates queries the "Certificates" edge of the Users entity.
func (_m *Users) QueryCertificates() *CertificatesQuery {
	return NewUsersClient(_m.config).QueryCertificates(_m)
}

// QueryNotifications queries the "Notifications" edge of the Users entity.
func (_m *Users) QueryNotifications() *NotificationsQuery {
	return NewUsersClient(_m.config).QueryNotifications(_m)
}

// Update returns a builder for updating this Users.
// Note that you need to call Users.Unwrap() before calling this method if this Users
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Users) Update() *UsersUpdateOne {
	return NewUsersClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Users entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Users) Unwrap() *Users {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Users is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Users) String() string {
	var builder strings.Builder
	builder.WriteString("Users(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteString(", ")
	if v := _m.FullName; v != nil {
		builder.WriteString("full_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Avatar; v != nil {
		builder.WriteString("avatar=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsersSlice is a parsable slice of Users.
type UsersSlice []*Users
