services:
  lms-mysql:
    container_name: lms-mysql
    image: mysql:latest
    volumes:
      - lms-mysql:/var/lib/mysql
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=lms-backend
    networks:
      - lms-network

  lms-redis:
    container_name: lms-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - lms-network

  lms-elasticsearch:
    container_name: lms-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - lms-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 1g
    networks:
      - lms-network

  lms-kibana:
    container_name: lms-kibana
    image: docker.elastic.co/kibana/kibana:8.13.0
    ports:
      - "5601:5601"
    networks:
      - lms-network

  lms-rabbitmq:
    container_name: lms-rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  lms-mysql:
  lms-elasticsearch:
