// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// CertificatesColumns holds the columns for the "certificates" table.
	CertificatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "issued_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "course_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// CertificatesTable holds the schema information for the "certificates" table.
	CertificatesTable = &schema.Table{
		Name:       "certificates",
		Columns:    CertificatesColumns,
		PrimaryKey: []*schema.Column{CertificatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "certificates_courses_Certificates",
				Columns:    []*schema.Column{CertificatesColumns[4]},
				RefColumns: []*schema.Column{CoursesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "certificates_users_Certificates",
				Columns:    []*schema.Column{CertificatesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CoursesColumns holds the columns for the "courses" table.
	CoursesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "thumbnail", Type: field.TypeString, Nullable: true},
		{Name: "price", Type: field.TypeFloat64, Default: 0},
		{Name: "level", Type: field.TypeEnum, Enums: []string{"beginner", "intermediate", "advanced"}, Default: "beginner"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "published", "archived"}, Default: "draft"},
		{Name: "total_lessons", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "category_id", Type: field.TypeInt},
	}
	// CoursesTable holds the schema information for the "courses" table.
	CoursesTable = &schema.Table{
		Name:       "courses",
		Columns:    CoursesColumns,
		PrimaryKey: []*schema.Column{CoursesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "courses_categories_Courses",
				Columns:    []*schema.Column{CoursesColumns[12]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// EnrollmentsColumns holds the columns for the "enrollments" table.
	EnrollmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "completed", "cancelled"}, Default: "active"},
		{Name: "progress_percent", Type: field.TypeFloat64, Default: 0},
		{Name: "enrolled_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "course_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// EnrollmentsTable holds the schema information for the "enrollments" table.
	EnrollmentsTable = &schema.Table{
		Name:       "enrollments",
		Columns:    EnrollmentsColumns,
		PrimaryKey: []*schema.Column{EnrollmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "enrollments_courses_Enrollments",
				Columns:    []*schema.Column{EnrollmentsColumns[7]},
				RefColumns: []*schema.Column{CoursesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "enrollments_users_Enrollments",
				Columns:    []*schema.Column{EnrollmentsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LessonProgressesColumns holds the columns for the "lesson_progresses" table.
	LessonProgressesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "is_completed", Type: field.TypeBool, Default: false},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "course_id", Type: field.TypeInt},
		{Name: "lesson_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// LessonProgressesTable holds the schema information for the "lesson_progresses" table.
	LessonProgressesTable = &schema.Table{
		Name:       "lesson_progresses",
		Columns:    LessonProgressesColumns,
		PrimaryKey: []*schema.Column{LessonProgressesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "lesson_progresses_courses_LessonProgresses",
				Columns:    []*schema.Column{LessonProgressesColumns[5]},
				RefColumns: []*schema.Column{CoursesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "lesson_progresses_lessons_LessonProgresses",
				Columns:    []*schema.Column{LessonProgressesColumns[6]},
				RefColumns: []*schema.Column{LessonsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "lesson_progresses_users_LessonProgresses",
				Columns:    []*schema.Column{LessonProgressesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LessonsColumns holds the columns for the "lessons" table.
	LessonsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "video_url", Type: field.TypeString, Nullable: true},
		{Name: "duration_minutes", Type: field.TypeInt, Default: 0},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "is_preview", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "course_id", Type: field.TypeInt},
		{Name: "section_id", Type: field.TypeInt},
	}
	// LessonsTable holds the schema information for the "lessons" table.
	LessonsTable = &schema.Table{
		Name:       "lessons",
		Columns:    LessonsColumns,
		PrimaryKey: []*schema.Column{LessonsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "lessons_courses_Lessons",
				Columns:    []*schema.Column{LessonsColumns[10]},
				RefColumns: []*schema.Column{CoursesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "lessons_sections_Lessons",
				Columns:    []*schema.Column{LessonsColumns[11]},
				RefColumns: []*schema.Column{SectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "is_read", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notifications_users_Notifications",
				Columns:    []*schema.Column{NotificationsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// QuestionsColumns holds the columns for the "questions" table.
	QuestionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "question_text", Type: field.TypeString, Size: 2147483647},
		{Name: "option_a", Type: field.TypeString},
		{Name: "option_b", Type: field.TypeString},
		{Name: "option_c", Type: field.TypeString},
		{Name: "option_d", Type: field.TypeString},
		{Name: "correct_option", Type: field.TypeEnum, Enums: []string{"A", "B", "C", "D"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "quiz_id", Type: field.TypeInt},
	}
	// QuestionsTable holds the schema information for the "questions" table.
	QuestionsTable = &schema.Table{
		Name:       "questions",
		Columns:    QuestionsColumns,
		PrimaryKey: []*schema.Column{QuestionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "questions_quizzes_Questions",
				Columns:    []*schema.Column{QuestionsColumns[10]},
				RefColumns: []*schema.Column{QuizzesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// QuizAttemptsColumns holds the columns for the "quiz_attempts" table.
	QuizAttemptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "score", Type: field.TypeFloat64, Default: 0},
		{Name: "total_questions", Type: field.TypeInt, Default: 0},
		{Name: "correct_answers", Type: field.TypeInt, Default: 0},
		{Name: "is_passed", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "quiz_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// QuizAttemptsTable holds the schema information for the "quiz_attempts" table.
	QuizAttemptsTable = &schema.Table{
		Name:       "quiz_attempts",
		Columns:    QuizAttemptsColumns,
		PrimaryKey: []*schema.Column{QuizAttemptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "quiz_attempts_quizzes_QuizAttempts",
				Columns:    []*schema.Column{QuizAttemptsColumns[6]},
				RefColumns: []*schema.Column{QuizzesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "quiz_attempts_users_QuizAttempts",
				Columns:    []*schema.Column{QuizAttemptsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// QuizzesColumns holds the columns for the "quizzes" table.
	QuizzesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "passing_score", Type: field.TypeInt, Default: 70},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "course_id", Type: field.TypeInt},
		{Name: "lesson_id", Type: field.TypeInt},
	}
	// QuizzesTable holds the schema information for the "quizzes" table.
	QuizzesTable = &schema.Table{
		Name:       "quizzes",
		Columns:    QuizzesColumns,
		PrimaryKey: []*schema.Column{QuizzesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "quizzes_courses_Quizzes",
				Columns:    []*schema.Column{QuizzesColumns[6]},
				RefColumns: []*schema.Column{CoursesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "quizzes_lessons_Quizzes",
				Columns:    []*schema.Column{QuizzesColumns[7]},
				RefColumns: []*schema.Column{LessonsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SectionsColumns holds the columns for the "sections" table.
	SectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "course_id", Type: field.TypeInt},
	}
	// SectionsTable holds the schema information for the "sections" table.
	SectionsTable = &schema.Table{
		Name:       "sections",
		Columns:    SectionsColumns,
		PrimaryKey: []*schema.Column{SectionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sections_courses_Sections",
				Columns:    []*schema.Column{SectionsColumns[6]},
				RefColumns: []*schema.Column{CoursesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "full_name", Type: field.TypeString, Nullable: true},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"student", "admin"}, Default: "student"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "blocked"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		CertificatesTable,
		CoursesTable,
		EnrollmentsTable,
		LessonProgressesTable,
		LessonsTable,
		NotificationsTable,
		QuestionsTable,
		QuizAttemptsTable,
		QuizzesTable,
		SectionsTable,
		UsersTable,
	}
)

func init() {
	CertificatesTable.ForeignKeys[0].RefTable = CoursesTable
	CertificatesTable.ForeignKeys[1].RefTable = UsersTable
	CoursesTable.ForeignKeys[0].RefTable = CategoriesTable
	EnrollmentsTable.ForeignKeys[0].RefTable = CoursesTable
	EnrollmentsTable.ForeignKeys[1].RefTable = UsersTable
	LessonProgressesTable.ForeignKeys[0].RefTable = CoursesTable
	LessonProgressesTable.ForeignKeys[1].RefTable = LessonsTable
	LessonProgressesTable.ForeignKeys[2].RefTable = UsersTable
	LessonsTable.ForeignKeys[0].RefTable = CoursesTable
	LessonsTable.ForeignKeys[1].RefTable = SectionsTable
	NotificationsTable.ForeignKeys[0].RefTable = UsersTable
	QuestionsTable.ForeignKeys[0].RefTable = QuizzesTable
	QuizAttemptsTable.ForeignKeys[0].RefTable = QuizzesTable
	QuizAttemptsTable.ForeignKeys[1].RefTable = UsersTable
	QuizzesTable.ForeignKeys[0].RefTable = CoursesTable
	QuizzesTable.ForeignKeys[1].RefTable = LessonsTable
	SectionsTable.ForeignKeys[0].RefTable = CoursesTable
}
