// Code generated by ent, DO NOT EDIT.

package quizattempts

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the quizattempts type in the database.
	Label = "quiz_attempts"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldQuizID holds the string denoting the quiz_id field in the database.
	FieldQuizID = "quiz_id"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldTotalQuestions holds the string denoting the total_questions field in the database.
	FieldTotalQuestions = "total_questions"
	// FieldCorrectAnswers holds the string denoting the correct_answers field in the database.
	FieldCorrectAnswers = "correct_answers"
	// FieldIsPassed holds the string denoting the is_passed field in the database.
	FieldIsPassed = "is_passed"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "Users"
	// EdgeQuizzes holds the string denoting the quizzes edge name in mutations.
	EdgeQuizzes = "Quizzes"
	// Table holds the table name of the quizattempts in the database.
	Table = "quiz_attempts"
	// UsersTable is the table that holds the Users relation/edge.
	UsersTable = "quiz_attempts"
	// UsersInverseTable is the table name for the Users entity.
	// It exists in this package in order to avoid circular dependency with the "users" package.
	UsersInverseTable = "users"
	// UsersColumn is the table column denoting the Users relation/edge.
	UsersColumn = "user_id"
	// QuizzesTable is the table that holds the Quizzes relation/edge.
	QuizzesTable = "quiz_attempts"
	// QuizzesInverseTable is the table name for the Quizzes entity.
	// It exists in this package in order to avoid circular dependency with the "quizzes" package.
	QuizzesInverseTable = "quizzes"
	// QuizzesColumn is the table column denoting the Quizzes relation/edge.
	QuizzesColumn = "quiz_id"
)

// Columns holds all SQL columns for quizattempts fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldQuizID,
	FieldScore,
	FieldTotalQuestions,
	FieldCorrectAnswers,
	FieldIsPassed,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore float64
	// DefaultTotalQuestions holds the default value on creation for the "total_questions" field.
	DefaultTotalQuestions int
	// DefaultCorrectAnswers holds the default value on creation for the "correct_answers" field.
	DefaultCorrectAnswers int
	// DefaultIsPassed holds the default value on creation for the "is_passed" field.
	DefaultIsPassed bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the QuizAttempts queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByQuizID orders the results by the quiz_id field.
func ByQuizID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuizID, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByTotalQuestions orders the results by the total_questions field.
func ByTotalQuestions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalQuestions, opts...).ToFunc()
}

// ByCorrectAnswers orders the results by the correct_answers field.
func ByCorrectAnswers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCorrectAnswers, opts...).ToFunc()
}

// ByIsPassed orders the results by the is_passed field.
func ByIsPassed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPassed, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUsersField orders the results by Users field.
func ByUsersField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsersStep(), sql.OrderByField(field, opts...))
	}
}

// ByQuizzesField orders the results by Quizzes field.
func ByQuizzesField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuizzesStep(), sql.OrderByField(field, opts...))
	}
}
func newUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UsersTable, UsersColumn),
	)
}
func newQuizzesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuizzesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, QuizzesTable, QuizzesColumn),
	)
}
