// Code generated by ent, DO NOT EDIT.

package quizattempts

import (
	"lms-api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldUserID, v))
}

// QuizID applies equality check predicate on the "quiz_id" field. It's identical to QuizIDEQ.
func QuizID(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldQuizID, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v float64) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldScore, v))
}

// TotalQuestions applies equality check predicate on the "total_questions" field. It's identical to TotalQuestionsEQ.
func TotalQuestions(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldTotalQuestions, v))
}

// CorrectAnswers applies equality check predicate on the "correct_answers" field. It's identical to CorrectAnswersEQ.
func CorrectAnswers(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldCorrectAnswers, v))
}

// IsPassed applies equality check predicate on the "is_passed" field. It's identical to IsPassedEQ.
func IsPassed(v bool) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldIsPassed, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNotIn(FieldUserID, vs...))
}

// QuizIDEQ applies the EQ predicate on the "quiz_id" field.
func QuizIDEQ(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldQuizID, v))
}

// QuizIDNEQ applies the NEQ predicate on the "quiz_id" field.
func QuizIDNEQ(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNEQ(FieldQuizID, v))
}

// QuizIDIn applies the In predicate on the "quiz_id" field.
func QuizIDIn(vs ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldIn(FieldQuizID, vs...))
}

// QuizIDNotIn applies the NotIn predicate on the "quiz_id" field.
func QuizIDNotIn(vs ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNotIn(FieldQuizID, vs...))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v float64) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v float64) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...float64) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...float64) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v float64) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v float64) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v float64) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v float64) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLTE(FieldScore, v))
}

// TotalQuestionsEQ applies the EQ predicate on the "total_questions" field.
func TotalQuestionsEQ(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldTotalQuestions, v))
}

// TotalQuestionsNEQ applies the NEQ predicate on the "total_questions" field.
func TotalQuestionsNEQ(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNEQ(FieldTotalQuestions, v))
}

// TotalQuestionsIn applies the In predicate on the "total_questions" field.
func TotalQuestionsIn(vs ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldIn(FieldTotalQuestions, vs...))
}

// TotalQuestionsNotIn applies the NotIn predicate on the "total_questions" field.
func TotalQuestionsNotIn(vs ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNotIn(FieldTotalQuestions, vs...))
}

// TotalQuestionsGT applies the GT predicate on the "total_questions" field.
func TotalQuestionsGT(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGT(FieldTotalQuestions, v))
}

// TotalQuestionsGTE applies the GTE predicate on the "total_questions" field.
func TotalQuestionsGTE(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGTE(FieldTotalQuestions, v))
}

// TotalQuestionsLT applies the LT predicate on the "total_questions" field.
func TotalQuestionsLT(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLT(FieldTotalQuestions, v))
}

// TotalQuestionsLTE applies the LTE predicate on the "total_questions" field.
func TotalQuestionsLTE(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLTE(FieldTotalQuestions, v))
}

// CorrectAnswersEQ applies the EQ predicate on the "correct_answers" field.
func CorrectAnswersEQ(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldCorrectAnswers, v))
}

// CorrectAnswersNEQ applies the NEQ predicate on the "correct_answers" field.
func CorrectAnswersNEQ(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNEQ(FieldCorrectAnswers, v))
}

// CorrectAnswersIn applies the In predicate on the "correct_answers" field.
func CorrectAnswersIn(vs ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldIn(FieldCorrectAnswers, vs...))
}

// CorrectAnswersNotIn applies the NotIn predicate on the "correct_answers" field.
func CorrectAnswersNotIn(vs ...int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNotIn(FieldCorrectAnswers, vs...))
}

// CorrectAnswersGT applies the GT predicate on the "correct_answers" field.
func CorrectAnswersGT(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGT(FieldCorrectAnswers, v))
}

// CorrectAnswersGTE applies the GTE predicate on the "correct_answers" field.
func CorrectAnswersGTE(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGTE(FieldCorrectAnswers, v))
}

// CorrectAnswersLT applies the LT predicate on the "correct_answers" field.
func CorrectAnswersLT(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLT(FieldCorrectAnswers, v))
}

// CorrectAnswersLTE applies the LTE predicate on the "correct_answers" field.
func CorrectAnswersLTE(v int) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLTE(FieldCorrectAnswers, v))
}

// IsPassedEQ applies the EQ predicate on the "is_passed" field.
func IsPassedEQ(v bool) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldIsPassed, v))
}

// IsPassedNEQ applies the NEQ predicate on the "is_passed" field.
func IsPassedNEQ(v bool) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNEQ(FieldIsPassed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUsers applies the HasEdge predicate on the "Users" edge.
func HasUsers() predicate.QuizAttempts {
	return predicate.QuizAttempts(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "Users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.Users) predicate.QuizAttempts {
	return predicate.QuizAttempts(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQuizzes applies the HasEdge predicate on the "Quizzes" edge.
func HasQuizzes() predicate.QuizAttempts {
	return predicate.QuizAttempts(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuizzesTable, QuizzesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuizzesWith applies the HasEdge predicate on the "Quizzes" edge with a given conditions (other predicates).
func HasQuizzesWith(preds ...predicate.Quizzes) predicate.QuizAttempts {
	return predicate.QuizAttempts(func(s *sql.Selector) {
		step := newQuizzesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuizAttempts) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuizAttempts) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuizAttempts) predicate.QuizAttempts {
	return predicate.QuizAttempts(sql.NotPredicates(p))
}
