// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-backend/ent/courses"
	"lms-backend/ent/enrollments"
	"lms-backend/ent/predicate"
	"lms-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnrollmentsUpdate is the builder for updating Enrollments entities.
type EnrollmentsUpdate struct {
	config
	hooks    []Hook
	mutation *EnrollmentsMutation
}

// Where appends a list predicates to the EnrollmentsUpdate builder.
func (_u *EnrollmentsUpdate) Where(ps ...predicate.Enrollments) *EnrollmentsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EnrollmentsUpdate) SetUserID(v int) *EnrollmentsUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EnrollmentsUpdate) SetNillableUserID(v *int) *EnrollmentsUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *EnrollmentsUpdate) SetCourseID(v int) *EnrollmentsUpdate {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *EnrollmentsUpdate) SetNillableCourseID(v *int) *EnrollmentsUpdate {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnrollmentsUpdate) SetStatus(v enrollments.Status) *EnrollmentsUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnrollmentsUpdate) SetNillableStatus(v *enrollments.Status) *EnrollmentsUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgressPercent sets the "progress_percent" field.
func (_u *EnrollmentsUpdate) SetProgressPercent(v float64) *EnrollmentsUpdate {
	_u.mutation.ResetProgressPercent()
	_u.mutation.SetProgressPercent(v)
	return _u
}

// SetNillableProgressPercent sets the "progress_percent" field if the given value is not nil.
func (_u *EnrollmentsUpdate) SetNillableProgressPercent(v *float64) *EnrollmentsUpdate {
	if v != nil {
		_u.SetProgressPercent(*v)
	}
	return _u
}

// AddProgressPercent adds value to the "progress_percent" field.
func (_u *EnrollmentsUpdate) AddProgressPercent(v float64) *EnrollmentsUpdate {
	_u.mutation.AddProgressPercent(v)
	return _u
}

// SetEnrolledAt sets the "enrolled_at" field.
func (_u *EnrollmentsUpdate) SetEnrolledAt(v time.Time) *EnrollmentsUpdate {
	_u.mutation.SetEnrolledAt(v)
	return _u
}

// SetNillableEnrolledAt sets the "enrolled_at" field if the given value is not nil.
func (_u *EnrollmentsUpdate) SetNillableEnrolledAt(v *time.Time) *EnrollmentsUpdate {
	if v != nil {
		_u.SetEnrolledAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *EnrollmentsUpdate) SetCompletedAt(v time.Time) *EnrollmentsUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *EnrollmentsUpdate) SetNillableCompletedAt(v *time.Time) *EnrollmentsUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *EnrollmentsUpdate) ClearCompletedAt() *EnrollmentsUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnrollmentsUpdate) SetUpdatedAt(v time.Time) *EnrollmentsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *EnrollmentsUpdate) SetUsersID(id int) *EnrollmentsUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *EnrollmentsUpdate) SetUsers(v *Users) *EnrollmentsUpdate {
	return _u.SetUsersID(v.ID)
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *EnrollmentsUpdate) SetCoursesID(id int) *EnrollmentsUpdate {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *EnrollmentsUpdate) SetCourses(v *Courses) *EnrollmentsUpdate {
	return _u.SetCoursesID(v.ID)
}

// Mutation returns the EnrollmentsMutation object of the builder.
func (_u *EnrollmentsUpdate) Mutation() *EnrollmentsMutation {
	return _u.mutation
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *EnrollmentsUpdate) ClearUsers() *EnrollmentsUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *EnrollmentsUpdate) ClearCourses() *EnrollmentsUpdate {
	_u.mutation.ClearCourses()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnrollmentsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnrollmentsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnrollmentsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnrollmentsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnrollmentsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enrollments.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnrollmentsUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := enrollments.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Enrollments.status": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Enrollments.Users"`)
	}
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Enrollments.Courses"`)
	}
	return nil
}

func (_u *EnrollmentsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enrollments.Table, enrollments.Columns, sqlgraph.NewFieldSpec(enrollments.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enrollments.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProgressPercent(); ok {
		_spec.SetField(enrollments.FieldProgressPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProgressPercent(); ok {
		_spec.AddField(enrollments.FieldProgressPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnrolledAt(); ok {
		_spec.SetField(enrollments.FieldEnrolledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(enrollments.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(enrollments.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enrollments.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.UsersTable,
			Columns: []string{enrollments.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.UsersTable,
			Columns: []string{enrollments.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.CoursesTable,
			Columns: []string{enrollments.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.CoursesTable,
			Columns: []string{enrollments.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enrollments.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnrollmentsUpdateOne is the builder for updating a single Enrollments entity.
type EnrollmentsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnrollmentsMutation
}

// SetUserID sets the "user_id" field.
func (_u *EnrollmentsUpdateOne) SetUserID(v int) *EnrollmentsUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EnrollmentsUpdateOne) SetNillableUserID(v *int) *EnrollmentsUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *EnrollmentsUpdateOne) SetCourseID(v int) *EnrollmentsUpdateOne {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *EnrollmentsUpdateOne) SetNillableCourseID(v *int) *EnrollmentsUpdateOne {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnrollmentsUpdateOne) SetStatus(v enrollments.Status) *EnrollmentsUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnrollmentsUpdateOne) SetNillableStatus(v *enrollments.Status) *EnrollmentsUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgressPercent sets the "progress_percent" field.
func (_u *EnrollmentsUpdateOne) SetProgressPercent(v float64) *EnrollmentsUpdateOne {
	_u.mutation.ResetProgressPercent()
	_u.mutation.SetProgressPercent(v)
	return _u
}

// SetNillableProgressPercent sets the "progress_percent" field if the given value is not nil.
func (_u *EnrollmentsUpdateOne) SetNillableProgressPercent(v *float64) *EnrollmentsUpdateOne {
	if v != nil {
		_u.SetProgressPercent(*v)
	}
	return _u
}

// AddProgressPercent adds value to the "progress_percent" field.
func (_u *EnrollmentsUpdateOne) AddProgressPercent(v float64) *EnrollmentsUpdateOne {
	_u.mutation.AddProgressPercent(v)
	return _u
}

// SetEnrolledAt sets the "enrolled_at" field.
func (_u *EnrollmentsUpdateOne) SetEnrolledAt(v time.Time) *EnrollmentsUpdateOne {
	_u.mutation.SetEnrolledAt(v)
	return _u
}

// SetNillableEnrolledAt sets the "enrolled_at" field if the given value is not nil.
func (_u *EnrollmentsUpdateOne) SetNillableEnrolledAt(v *time.Time) *EnrollmentsUpdateOne {
	if v != nil {
		_u.SetEnrolledAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *EnrollmentsUpdateOne) SetCompletedAt(v time.Time) *EnrollmentsUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *EnrollmentsUpdateOne) SetNillableCompletedAt(v *time.Time) *EnrollmentsUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *EnrollmentsUpdateOne) ClearCompletedAt() *EnrollmentsUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnrollmentsUpdateOne) SetUpdatedAt(v time.Time) *EnrollmentsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *EnrollmentsUpdateOne) SetUsersID(id int) *EnrollmentsUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *EnrollmentsUpdateOne) SetUsers(v *Users) *EnrollmentsUpdateOne {
	return _u.SetUsersID(v.ID)
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *EnrollmentsUpdateOne) SetCoursesID(id int) *EnrollmentsUpdateOne {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *EnrollmentsUpdateOne) SetCourses(v *Courses) *EnrollmentsUpdateOne {
	return _u.SetCoursesID(v.ID)
}

// Mutation returns the EnrollmentsMutation object of the builder.
func (_u *EnrollmentsUpdateOne) Mutation() *EnrollmentsMutation {
	return _u.mutation
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *EnrollmentsUpdateOne) ClearUsers() *EnrollmentsUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *EnrollmentsUpdateOne) ClearCourses() *EnrollmentsUpdateOne {
	_u.mutation.ClearCourses()
	return _u
}

// Where appends a list predicates to the EnrollmentsUpdate builder.
func (_u *EnrollmentsUpdateOne) Where(ps ...predicate.Enrollments) *EnrollmentsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnrollmentsUpdateOne) Select(field string, fields ...string) *EnrollmentsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Enrollments entity.
func (_u *EnrollmentsUpdateOne) Save(ctx context.Context) (*Enrollments, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnrollmentsUpdateOne) SaveX(ctx context.Context) *Enrollments {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnrollmentsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnrollmentsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnrollmentsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enrollments.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnrollmentsUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := enrollments.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Enrollments.status": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Enrollments.Users"`)
	}
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Enrollments.Courses"`)
	}
	return nil
}

func (_u *EnrollmentsUpdateOne) sqlSave(ctx context.Context) (_node *Enrollments, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enrollments.Table, enrollments.Columns, sqlgraph.NewFieldSpec(enrollments.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Enrollments.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enrollments.FieldID)
		for _, f := range fields {
			if !enrollments.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enrollments.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enrollments.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProgressPercent(); ok {
		_spec.SetField(enrollments.FieldProgressPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProgressPercent(); ok {
		_spec.AddField(enrollments.FieldProgressPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnrolledAt(); ok {
		_spec.SetField(enrollments.FieldEnrolledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(enrollments.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(enrollments.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enrollments.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.UsersTable,
			Columns: []string{enrollments.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.UsersTable,
			Columns: []string{enrollments.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.CoursesTable,
			Columns: []string{enrollments.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.CoursesTable,
			Columns: []string{enrollments.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Enrollments{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enrollments.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
