// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-backend/ent/courses"
	"lms-backend/ent/enrollments"
	"lms-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnrollmentsCreate is the builder for creating a Enrollments entity.
type EnrollmentsCreate struct {
	config
	mutation *EnrollmentsMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *EnrollmentsCreate) SetUserID(v int) *EnrollmentsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCourseID sets the "course_id" field.
func (_c *EnrollmentsCreate) SetCourseID(v int) *EnrollmentsCreate {
	_c.mutation.SetCourseID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *EnrollmentsCreate) SetStatus(v enrollments.Status) *EnrollmentsCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EnrollmentsCreate) SetNillableStatus(v *enrollments.Status) *EnrollmentsCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProgressPercent sets the "progress_percent" field.
func (_c *EnrollmentsCreate) SetProgressPercent(v float64) *EnrollmentsCreate {
	_c.mutation.SetProgressPercent(v)
	return _c
}

// SetNillableProgressPercent sets the "progress_percent" field if the given value is not nil.
func (_c *EnrollmentsCreate) SetNillableProgressPercent(v *float64) *EnrollmentsCreate {
	if v != nil {
		_c.SetProgressPercent(*v)
	}
	return _c
}

// SetEnrolledAt sets the "enrolled_at" field.
func (_c *EnrollmentsCreate) SetEnrolledAt(v time.Time) *EnrollmentsCreate {
	_c.mutation.SetEnrolledAt(v)
	return _c
}

// SetNillableEnrolledAt sets the "enrolled_at" field if the given value is not nil.
func (_c *EnrollmentsCreate) SetNillableEnrolledAt(v *time.Time) *EnrollmentsCreate {
	if v != nil {
		_c.SetEnrolledAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *EnrollmentsCreate) SetCompletedAt(v time.Time) *EnrollmentsCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *EnrollmentsCreate) SetNillableCompletedAt(v *time.Time) *EnrollmentsCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnrollmentsCreate) SetCreatedAt(v time.Time) *EnrollmentsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnrollmentsCreate) SetNillableCreatedAt(v *time.Time) *EnrollmentsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnrollmentsCreate) SetUpdatedAt(v time.Time) *EnrollmentsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnrollmentsCreate) SetNillableUpdatedAt(v *time.Time) *EnrollmentsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_c *EnrollmentsCreate) SetUsersID(id int) *EnrollmentsCreate {
	_c.mutation.SetUsersID(id)
	return _c
}

// SetUsers sets the "Users" edge to the Users entity.
func (_c *EnrollmentsCreate) SetUsers(v *Users) *EnrollmentsCreate {
	return _c.SetUsersID(v.ID)
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_c *EnrollmentsCreate) SetCoursesID(id int) *EnrollmentsCreate {
	_c.mutation.SetCoursesID(id)
	return _c
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_c *EnrollmentsCreate) SetCourses(v *Courses) *EnrollmentsCreate {
	return _c.SetCoursesID(v.ID)
}

// Mutation returns the EnrollmentsMutation object of the builder.
func (_c *EnrollmentsCreate) Mutation() *EnrollmentsMutation {
	return _c.mutation
}

// Save creates the Enrollments in the database.
func (_c *EnrollmentsCreate) Save(ctx context.Context) (*Enrollments, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnrollmentsCreate) SaveX(ctx context.Context) *Enrollments {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnrollmentsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnrollmentsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnrollmentsCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := enrollments.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ProgressPercent(); !ok {
		v := enrollments.DefaultProgressPercent
		_c.mutation.SetProgressPercent(v)
	}
	if _, ok := _c.mutation.EnrolledAt(); !ok {
		v := enrollments.DefaultEnrolledAt()
		_c.mutation.SetEnrolledAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := enrollments.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := enrollments.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnrollmentsCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Enrollments.user_id"`)}
	}
	if _, ok := _c.mutation.CourseID(); !ok {
		return &ValidationError{Name: "course_id", err: errors.New(`ent: missing required field "Enrollments.course_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Enrollments.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := enrollments.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Enrollments.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProgressPercent(); !ok {
		return &ValidationError{Name: "progress_percent", err: errors.New(`ent: missing required field "Enrollments.progress_percent"`)}
	}
	if _, ok := _c.mutation.EnrolledAt(); !ok {
		return &ValidationError{Name: "enrolled_at", err: errors.New(`ent: missing required field "Enrollments.enrolled_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Enrollments.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Enrollments.updated_at"`)}
	}
	if len(_c.mutation.UsersIDs()) == 0 {
		return &ValidationError{Name: "Users", err: errors.New(`ent: missing required edge "Enrollments.Users"`)}
	}
	if len(_c.mutation.CoursesIDs()) == 0 {
		return &ValidationError{Name: "Courses", err: errors.New(`ent: missing required edge "Enrollments.Courses"`)}
	}
	return nil
}

func (_c *EnrollmentsCreate) sqlSave(ctx context.Context) (*Enrollments, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnrollmentsCreate) createSpec() (*Enrollments, *sqlgraph.CreateSpec) {
	var (
		_node = &Enrollments{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enrollments.Table, sqlgraph.NewFieldSpec(enrollments.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(enrollments.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProgressPercent(); ok {
		_spec.SetField(enrollments.FieldProgressPercent, field.TypeFloat64, value)
		_node.ProgressPercent = value
	}
	if value, ok := _c.mutation.EnrolledAt(); ok {
		_spec.SetField(enrollments.FieldEnrolledAt, field.TypeTime, value)
		_node.EnrolledAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(enrollments.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enrollments.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(enrollments.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.UsersTable,
			Columns: []string{enrollments.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enrollments.CoursesTable,
			Columns: []string{enrollments.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CourseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EnrollmentsCreateBulk is the builder for creating many Enrollments entities in bulk.
type EnrollmentsCreateBulk struct {
	config
	err      error
	builders []*EnrollmentsCreate
}

// Save creates the Enrollments entities in the database.
func (_c *EnrollmentsCreateBulk) Save(ctx context.Context) ([]*Enrollments, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Enrollments, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnrollmentsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnrollmentsCreateBulk) SaveX(ctx context.Context) []*Enrollments {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnrollmentsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnrollmentsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
