// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-backend/ent/courses"
	"lms-backend/ent/lessonprogresses"
	"lms-backend/ent/lessons"
	"lms-backend/ent/predicate"
	"lms-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LessonProgressesUpdate is the builder for updating LessonProgresses entities.
type LessonProgressesUpdate struct {
	config
	hooks    []Hook
	mutation *LessonProgressesMutation
}

// Where appends a list predicates to the LessonProgressesUpdate builder.
func (_u *LessonProgressesUpdate) Where(ps ...predicate.LessonProgresses) *LessonProgressesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LessonProgressesUpdate) SetUserID(v int) *LessonProgressesUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LessonProgressesUpdate) SetNillableUserID(v *int) *LessonProgressesUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *LessonProgressesUpdate) SetCourseID(v int) *LessonProgressesUpdate {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *LessonProgressesUpdate) SetNillableCourseID(v *int) *LessonProgressesUpdate {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetLessonID sets the "lesson_id" field.
func (_u *LessonProgressesUpdate) SetLessonID(v int) *LessonProgressesUpdate {
	_u.mutation.SetLessonID(v)
	return _u
}

// SetNillableLessonID sets the "lesson_id" field if the given value is not nil.
func (_u *LessonProgressesUpdate) SetNillableLessonID(v *int) *LessonProgressesUpdate {
	if v != nil {
		_u.SetLessonID(*v)
	}
	return _u
}

// SetIsCompleted sets the "is_completed" field.
func (_u *LessonProgressesUpdate) SetIsCompleted(v bool) *LessonProgressesUpdate {
	_u.mutation.SetIsCompleted(v)
	return _u
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_u *LessonProgressesUpdate) SetNillableIsCompleted(v *bool) *LessonProgressesUpdate {
	if v != nil {
		_u.SetIsCompleted(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *LessonProgressesUpdate) SetCompletedAt(v time.Time) *LessonProgressesUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *LessonProgressesUpdate) SetNillableCompletedAt(v *time.Time) *LessonProgressesUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *LessonProgressesUpdate) ClearCompletedAt() *LessonProgressesUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LessonProgressesUpdate) SetUpdatedAt(v time.Time) *LessonProgressesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *LessonProgressesUpdate) SetUsersID(id int) *LessonProgressesUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *LessonProgressesUpdate) SetUsers(v *Users) *LessonProgressesUpdate {
	return _u.SetUsersID(v.ID)
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *LessonProgressesUpdate) SetCoursesID(id int) *LessonProgressesUpdate {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *LessonProgressesUpdate) SetCourses(v *Courses) *LessonProgressesUpdate {
	return _u.SetCoursesID(v.ID)
}

// SetLessonsID sets the "Lessons" edge to the Lessons entity by ID.
func (_u *LessonProgressesUpdate) SetLessonsID(id int) *LessonProgressesUpdate {
	_u.mutation.SetLessonsID(id)
	return _u
}

// SetLessons sets the "Lessons" edge to the Lessons entity.
func (_u *LessonProgressesUpdate) SetLessons(v *Lessons) *LessonProgressesUpdate {
	return _u.SetLessonsID(v.ID)
}

// Mutation returns the LessonProgressesMutation object of the builder.
func (_u *LessonProgressesUpdate) Mutation() *LessonProgressesMutation {
	return _u.mutation
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *LessonProgressesUpdate) ClearUsers() *LessonProgressesUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *LessonProgressesUpdate) ClearCourses() *LessonProgressesUpdate {
	_u.mutation.ClearCourses()
	return _u
}

// ClearLessons clears the "Lessons" edge to the Lessons entity.
func (_u *LessonProgressesUpdate) ClearLessons() *LessonProgressesUpdate {
	_u.mutation.ClearLessons()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LessonProgressesUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LessonProgressesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LessonProgressesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LessonProgressesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LessonProgressesUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lessonprogresses.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LessonProgressesUpdate) check() error {
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LessonProgresses.Users"`)
	}
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LessonProgresses.Courses"`)
	}
	if _u.mutation.LessonsCleared() && len(_u.mutation.LessonsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LessonProgresses.Lessons"`)
	}
	return nil
}

func (_u *LessonProgressesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lessonprogresses.Table, lessonprogresses.Columns, sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsCompleted(); ok {
		_spec.SetField(lessonprogresses.FieldIsCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(lessonprogresses.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(lessonprogresses.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lessonprogresses.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.UsersTable,
			Columns: []string{lessonprogresses.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.UsersTable,
			Columns: []string{lessonprogresses.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.CoursesTable,
			Columns: []string{lessonprogresses.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.CoursesTable,
			Columns: []string{lessonprogresses.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.LessonsTable,
			Columns: []string{lessonprogresses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.LessonsTable,
			Columns: []string{lessonprogresses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lessonprogresses.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LessonProgressesUpdateOne is the builder for updating a single LessonProgresses entity.
type LessonProgressesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LessonProgressesMutation
}

// SetUserID sets the "user_id" field.
func (_u *LessonProgressesUpdateOne) SetUserID(v int) *LessonProgressesUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LessonProgressesUpdateOne) SetNillableUserID(v *int) *LessonProgressesUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *LessonProgressesUpdateOne) SetCourseID(v int) *LessonProgressesUpdateOne {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *LessonProgressesUpdateOne) SetNillableCourseID(v *int) *LessonProgressesUpdateOne {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetLessonID sets the "lesson_id" field.
func (_u *LessonProgressesUpdateOne) SetLessonID(v int) *LessonProgressesUpdateOne {
	_u.mutation.SetLessonID(v)
	return _u
}

// SetNillableLessonID sets the "lesson_id" field if the given value is not nil.
func (_u *LessonProgressesUpdateOne) SetNillableLessonID(v *int) *LessonProgressesUpdateOne {
	if v != nil {
		_u.SetLessonID(*v)
	}
	return _u
}

// SetIsCompleted sets the "is_completed" field.
func (_u *LessonProgressesUpdateOne) SetIsCompleted(v bool) *LessonProgressesUpdateOne {
	_u.mutation.SetIsCompleted(v)
	return _u
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_u *LessonProgressesUpdateOne) SetNillableIsCompleted(v *bool) *LessonProgressesUpdateOne {
	if v != nil {
		_u.SetIsCompleted(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *LessonProgressesUpdateOne) SetCompletedAt(v time.Time) *LessonProgressesUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *LessonProgressesUpdateOne) SetNillableCompletedAt(v *time.Time) *LessonProgressesUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *LessonProgressesUpdateOne) ClearCompletedAt() *LessonProgressesUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LessonProgressesUpdateOne) SetUpdatedAt(v time.Time) *LessonProgressesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *LessonProgressesUpdateOne) SetUsersID(id int) *LessonProgressesUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *LessonProgressesUpdateOne) SetUsers(v *Users) *LessonProgressesUpdateOne {
	return _u.SetUsersID(v.ID)
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *LessonProgressesUpdateOne) SetCoursesID(id int) *LessonProgressesUpdateOne {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *LessonProgressesUpdateOne) SetCourses(v *Courses) *LessonProgressesUpdateOne {
	return _u.SetCoursesID(v.ID)
}

// SetLessonsID sets the "Lessons" edge to the Lessons entity by ID.
func (_u *LessonProgressesUpdateOne) SetLessonsID(id int) *LessonProgressesUpdateOne {
	_u.mutation.SetLessonsID(id)
	return _u
}

// SetLessons sets the "Lessons" edge to the Lessons entity.
func (_u *LessonProgressesUpdateOne) SetLessons(v *Lessons) *LessonProgressesUpdateOne {
	return _u.SetLessonsID(v.ID)
}

// Mutation returns the LessonProgressesMutation object of the builder.
func (_u *LessonProgressesUpdateOne) Mutation() *LessonProgressesMutation {
	return _u.mutation
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *LessonProgressesUpdateOne) ClearUsers() *LessonProgressesUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *LessonProgressesUpdateOne) ClearCourses() *LessonProgressesUpdateOne {
	_u.mutation.ClearCourses()
	return _u
}

// ClearLessons clears the "Lessons" edge to the Lessons entity.
func (_u *LessonProgressesUpdateOne) ClearLessons() *LessonProgressesUpdateOne {
	_u.mutation.ClearLessons()
	return _u
}

// Where appends a list predicates to the LessonProgressesUpdate builder.
func (_u *LessonProgressesUpdateOne) Where(ps ...predicate.LessonProgresses) *LessonProgressesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LessonProgressesUpdateOne) Select(field string, fields ...string) *LessonProgressesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LessonProgresses entity.
func (_u *LessonProgressesUpdateOne) Save(ctx context.Context) (*LessonProgresses, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LessonProgressesUpdateOne) SaveX(ctx context.Context) *LessonProgresses {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LessonProgressesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LessonProgressesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LessonProgressesUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lessonprogresses.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LessonProgressesUpdateOne) check() error {
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LessonProgresses.Users"`)
	}
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LessonProgresses.Courses"`)
	}
	if _u.mutation.LessonsCleared() && len(_u.mutation.LessonsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LessonProgresses.Lessons"`)
	}
	return nil
}

func (_u *LessonProgressesUpdateOne) sqlSave(ctx context.Context) (_node *LessonProgresses, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lessonprogresses.Table, lessonprogresses.Columns, sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LessonProgresses.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lessonprogresses.FieldID)
		for _, f := range fields {
			if !lessonprogresses.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lessonprogresses.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsCompleted(); ok {
		_spec.SetField(lessonprogresses.FieldIsCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(lessonprogresses.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(lessonprogresses.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lessonprogresses.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.UsersTable,
			Columns: []string{lessonprogresses.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.UsersTable,
			Columns: []string{lessonprogresses.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.CoursesTable,
			Columns: []string{lessonprogresses.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.CoursesTable,
			Columns: []string{lessonprogresses.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.LessonsTable,
			Columns: []string{lessonprogresses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessonprogresses.LessonsTable,
			Columns: []string{lessonprogresses.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LessonProgresses{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lessonprogresses.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
