// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-backend/ent/courses"
	"lms-backend/ent/lessonprogresses"
	"lms-backend/ent/lessons"
	"lms-backend/ent/predicate"
	"lms-backend/ent/quizzes"
	"lms-backend/ent/sections"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LessonsUpdate is the builder for updating Lessons entities.
type LessonsUpdate struct {
	config
	hooks    []Hook
	mutation *LessonsMutation
}

// Where appends a list predicates to the LessonsUpdate builder.
func (_u *LessonsUpdate) Where(ps ...predicate.Lessons) *LessonsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LessonsUpdate) SetDeletedAt(v time.Time) *LessonsUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LessonsUpdate) SetNillableDeletedAt(v *time.Time) *LessonsUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LessonsUpdate) ClearDeletedAt() *LessonsUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetSectionID sets the "section_id" field.
func (_u *LessonsUpdate) SetSectionID(v int) *LessonsUpdate {
	_u.mutation.SetSectionID(v)
	return _u
}

// SetNillableSectionID sets the "section_id" field if the given value is not nil.
func (_u *LessonsUpdate) SetNillableSectionID(v *int) *LessonsUpdate {
	if v != nil {
		_u.SetSectionID(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *LessonsUpdate) SetCourseID(v int) *LessonsUpdate {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *LessonsUpdate) SetNillableCourseID(v *int) *LessonsUpdate {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *LessonsUpdate) SetTitle(v string) *LessonsUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *LessonsUpdate) SetNillableTitle(v *string) *LessonsUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *LessonsUpdate) SetContent(v string) *LessonsUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *LessonsUpdate) SetNillableContent(v *string) *LessonsUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *LessonsUpdate) ClearContent() *LessonsUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetVideoURL sets the "video_url" field.
func (_u *LessonsUpdate) SetVideoURL(v string) *LessonsUpdate {
	_u.mutation.SetVideoURL(v)
	return _u
}

// SetNillableVideoURL sets the "video_url" field if the given value is not nil.
func (_u *LessonsUpdate) SetNillableVideoURL(v *string) *LessonsUpdate {
	if v != nil {
		_u.SetVideoURL(*v)
	}
	return _u
}

// ClearVideoURL clears the value of the "video_url" field.
func (_u *LessonsUpdate) ClearVideoURL() *LessonsUpdate {
	_u.mutation.ClearVideoURL()
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *LessonsUpdate) SetDurationMinutes(v int) *LessonsUpdate {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *LessonsUpdate) SetNillableDurationMinutes(v *int) *LessonsUpdate {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *LessonsUpdate) AddDurationMinutes(v int) *LessonsUpdate {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LessonsUpdate) SetSortOrder(v int) *LessonsUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LessonsUpdate) SetNillableSortOrder(v *int) *LessonsUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LessonsUpdate) AddSortOrder(v int) *LessonsUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsPreview sets the "is_preview" field.
func (_u *LessonsUpdate) SetIsPreview(v bool) *LessonsUpdate {
	_u.mutation.SetIsPreview(v)
	return _u
}

// SetNillableIsPreview sets the "is_preview" field if the given value is not nil.
func (_u *LessonsUpdate) SetNillableIsPreview(v *bool) *LessonsUpdate {
	if v != nil {
		_u.SetIsPreview(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LessonsUpdate) SetUpdatedAt(v time.Time) *LessonsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSectionsID sets the "Sections" edge to the Sections entity by ID.
func (_u *LessonsUpdate) SetSectionsID(id int) *LessonsUpdate {
	_u.mutation.SetSectionsID(id)
	return _u
}

// SetSections sets the "Sections" edge to the Sections entity.
func (_u *LessonsUpdate) SetSections(v *Sections) *LessonsUpdate {
	return _u.SetSectionsID(v.ID)
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *LessonsUpdate) SetCoursesID(id int) *LessonsUpdate {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *LessonsUpdate) SetCourses(v *Courses) *LessonsUpdate {
	return _u.SetCoursesID(v.ID)
}

// AddLessonProgressIDs adds the "LessonProgresses" edge to the LessonProgresses entity by IDs.
func (_u *LessonsUpdate) AddLessonProgressIDs(ids ...int) *LessonsUpdate {
	_u.mutation.AddLessonProgressIDs(ids...)
	return _u
}

// AddLessonProgresses adds the "LessonProgresses" edges to the LessonProgresses entity.
func (_u *LessonsUpdate) AddLessonProgresses(v ...*LessonProgresses) *LessonsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLessonProgressIDs(ids...)
}

// AddQuizzeIDs adds the "Quizzes" edge to the Quizzes entity by IDs.
func (_u *LessonsUpdate) AddQuizzeIDs(ids ...int) *LessonsUpdate {
	_u.mutation.AddQuizzeIDs(ids...)
	return _u
}

// AddQuizzes adds the "Quizzes" edges to the Quizzes entity.
func (_u *LessonsUpdate) AddQuizzes(v ...*Quizzes) *LessonsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuizzeIDs(ids...)
}

// Mutation returns the LessonsMutation object of the builder.
func (_u *LessonsUpdate) Mutation() *LessonsMutation {
	return _u.mutation
}

// ClearSections clears the "Sections" edge to the Sections entity.
func (_u *LessonsUpdate) ClearSections() *LessonsUpdate {
	_u.mutation.ClearSections()
	return _u
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *LessonsUpdate) ClearCourses() *LessonsUpdate {
	_u.mutation.ClearCourses()
	return _u
}

// ClearLessonProgresses clears all "LessonProgresses" edges to the LessonProgresses entity.
func (_u *LessonsUpdate) ClearLessonProgresses() *LessonsUpdate {
	_u.mutation.ClearLessonProgresses()
	return _u
}

// RemoveLessonProgressIDs removes the "LessonProgresses" edge to LessonProgresses entities by IDs.
func (_u *LessonsUpdate) RemoveLessonProgressIDs(ids ...int) *LessonsUpdate {
	_u.mutation.RemoveLessonProgressIDs(ids...)
	return _u
}

// RemoveLessonProgresses removes "LessonProgresses" edges to LessonProgresses entities.
func (_u *LessonsUpdate) RemoveLessonProgresses(v ...*LessonProgresses) *LessonsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLessonProgressIDs(ids...)
}

// ClearQuizzes clears all "Quizzes" edges to the Quizzes entity.
func (_u *LessonsUpdate) ClearQuizzes() *LessonsUpdate {
	_u.mutation.ClearQuizzes()
	return _u
}

// RemoveQuizzeIDs removes the "Quizzes" edge to Quizzes entities by IDs.
func (_u *LessonsUpdate) RemoveQuizzeIDs(ids ...int) *LessonsUpdate {
	_u.mutation.RemoveQuizzeIDs(ids...)
	return _u
}

// RemoveQuizzes removes "Quizzes" edges to Quizzes entities.
func (_u *LessonsUpdate) RemoveQuizzes(v ...*Quizzes) *LessonsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuizzeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LessonsUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LessonsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LessonsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LessonsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LessonsUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if lessons.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized lessons.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := lessons.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *LessonsUpdate) check() error {
	if _u.mutation.SectionsCleared() && len(_u.mutation.SectionsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Lessons.Sections"`)
	}
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Lessons.Courses"`)
	}
	return nil
}

func (_u *LessonsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lessons.Table, lessons.Columns, sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(lessons.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(lessons.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(lessons.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(lessons.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(lessons.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.VideoURL(); ok {
		_spec.SetField(lessons.FieldVideoURL, field.TypeString, value)
	}
	if _u.mutation.VideoURLCleared() {
		_spec.ClearField(lessons.FieldVideoURL, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(lessons.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(lessons.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(lessons.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(lessons.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPreview(); ok {
		_spec.SetField(lessons.FieldIsPreview, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lessons.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessons.SectionsTable,
			Columns: []string{lessons.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessons.SectionsTable,
			Columns: []string{lessons.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessons.CoursesTable,
			Columns: []string{lessons.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessons.CoursesTable,
			Columns: []string{lessons.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonProgressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.LessonProgressesTable,
			Columns: []string{lessons.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLessonProgressesIDs(); len(nodes) > 0 && !_u.mutation.LessonProgressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.LessonProgressesTable,
			Columns: []string{lessons.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonProgressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.LessonProgressesTable,
			Columns: []string{lessons.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.QuizzesTable,
			Columns: []string{lessons.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuizzesIDs(); len(nodes) > 0 && !_u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.QuizzesTable,
			Columns: []string{lessons.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.QuizzesTable,
			Columns: []string{lessons.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lessons.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LessonsUpdateOne is the builder for updating a single Lessons entity.
type LessonsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LessonsMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LessonsUpdateOne) SetDeletedAt(v time.Time) *LessonsUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LessonsUpdateOne) SetNillableDeletedAt(v *time.Time) *LessonsUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LessonsUpdateOne) ClearDeletedAt() *LessonsUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetSectionID sets the "section_id" field.
func (_u *LessonsUpdateOne) SetSectionID(v int) *LessonsUpdateOne {
	_u.mutation.SetSectionID(v)
	return _u
}

// SetNillableSectionID sets the "section_id" field if the given value is not nil.
func (_u *LessonsUpdateOne) SetNillableSectionID(v *int) *LessonsUpdateOne {
	if v != nil {
		_u.SetSectionID(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *LessonsUpdateOne) SetCourseID(v int) *LessonsUpdateOne {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *LessonsUpdateOne) SetNillableCourseID(v *int) *LessonsUpdateOne {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *LessonsUpdateOne) SetTitle(v string) *LessonsUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *LessonsUpdateOne) SetNillableTitle(v *string) *LessonsUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *LessonsUpdateOne) SetContent(v string) *LessonsUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *LessonsUpdateOne) SetNillableContent(v *string) *LessonsUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *LessonsUpdateOne) ClearContent() *LessonsUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetVideoURL sets the "video_url" field.
func (_u *LessonsUpdateOne) SetVideoURL(v string) *LessonsUpdateOne {
	_u.mutation.SetVideoURL(v)
	return _u
}

// SetNillableVideoURL sets the "video_url" field if the given value is not nil.
func (_u *LessonsUpdateOne) SetNillableVideoURL(v *string) *LessonsUpdateOne {
	if v != nil {
		_u.SetVideoURL(*v)
	}
	return _u
}

// ClearVideoURL clears the value of the "video_url" field.
func (_u *LessonsUpdateOne) ClearVideoURL() *LessonsUpdateOne {
	_u.mutation.ClearVideoURL()
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *LessonsUpdateOne) SetDurationMinutes(v int) *LessonsUpdateOne {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *LessonsUpdateOne) SetNillableDurationMinutes(v *int) *LessonsUpdateOne {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *LessonsUpdateOne) AddDurationMinutes(v int) *LessonsUpdateOne {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LessonsUpdateOne) SetSortOrder(v int) *LessonsUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LessonsUpdateOne) SetNillableSortOrder(v *int) *LessonsUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LessonsUpdateOne) AddSortOrder(v int) *LessonsUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsPreview sets the "is_preview" field.
func (_u *LessonsUpdateOne) SetIsPreview(v bool) *LessonsUpdateOne {
	_u.mutation.SetIsPreview(v)
	return _u
}

// SetNillableIsPreview sets the "is_preview" field if the given value is not nil.
func (_u *LessonsUpdateOne) SetNillableIsPreview(v *bool) *LessonsUpdateOne {
	if v != nil {
		_u.SetIsPreview(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LessonsUpdateOne) SetUpdatedAt(v time.Time) *LessonsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSectionsID sets the "Sections" edge to the Sections entity by ID.
func (_u *LessonsUpdateOne) SetSectionsID(id int) *LessonsUpdateOne {
	_u.mutation.SetSectionsID(id)
	return _u
}

// SetSections sets the "Sections" edge to the Sections entity.
func (_u *LessonsUpdateOne) SetSections(v *Sections) *LessonsUpdateOne {
	return _u.SetSectionsID(v.ID)
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *LessonsUpdateOne) SetCoursesID(id int) *LessonsUpdateOne {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *LessonsUpdateOne) SetCourses(v *Courses) *LessonsUpdateOne {
	return _u.SetCoursesID(v.ID)
}

// AddLessonProgressIDs adds the "LessonProgresses" edge to the LessonProgresses entity by IDs.
func (_u *LessonsUpdateOne) AddLessonProgressIDs(ids ...int) *LessonsUpdateOne {
	_u.mutation.AddLessonProgressIDs(ids...)
	return _u
}

// AddLessonProgresses adds the "LessonProgresses" edges to the LessonProgresses entity.
func (_u *LessonsUpdateOne) AddLessonProgresses(v ...*LessonProgresses) *LessonsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLessonProgressIDs(ids...)
}

// AddQuizzeIDs adds the "Quizzes" edge to the Quizzes entity by IDs.
func (_u *LessonsUpdateOne) AddQuizzeIDs(ids ...int) *LessonsUpdateOne {
	_u.mutation.AddQuizzeIDs(ids...)
	return _u
}

// AddQuizzes adds the "Quizzes" edges to the Quizzes entity.
func (_u *LessonsUpdateOne) AddQuizzes(v ...*Quizzes) *LessonsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuizzeIDs(ids...)
}

// Mutation returns the LessonsMutation object of the builder.
func (_u *LessonsUpdateOne) Mutation() *LessonsMutation {
	return _u.mutation
}

// ClearSections clears the "Sections" edge to the Sections entity.
func (_u *LessonsUpdateOne) ClearSections() *LessonsUpdateOne {
	_u.mutation.ClearSections()
	return _u
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *LessonsUpdateOne) ClearCourses() *LessonsUpdateOne {
	_u.mutation.ClearCourses()
	return _u
}

// ClearLessonProgresses clears all "LessonProgresses" edges to the LessonProgresses entity.
func (_u *LessonsUpdateOne) ClearLessonProgresses() *LessonsUpdateOne {
	_u.mutation.ClearLessonProgresses()
	return _u
}

// RemoveLessonProgressIDs removes the "LessonProgresses" edge to LessonProgresses entities by IDs.
func (_u *LessonsUpdateOne) RemoveLessonProgressIDs(ids ...int) *LessonsUpdateOne {
	_u.mutation.RemoveLessonProgressIDs(ids...)
	return _u
}

// RemoveLessonProgresses removes "LessonProgresses" edges to LessonProgresses entities.
func (_u *LessonsUpdateOne) RemoveLessonProgresses(v ...*LessonProgresses) *LessonsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLessonProgressIDs(ids...)
}

// ClearQuizzes clears all "Quizzes" edges to the Quizzes entity.
func (_u *LessonsUpdateOne) ClearQuizzes() *LessonsUpdateOne {
	_u.mutation.ClearQuizzes()
	return _u
}

// RemoveQuizzeIDs removes the "Quizzes" edge to Quizzes entities by IDs.
func (_u *LessonsUpdateOne) RemoveQuizzeIDs(ids ...int) *LessonsUpdateOne {
	_u.mutation.RemoveQuizzeIDs(ids...)
	return _u
}

// RemoveQuizzes removes "Quizzes" edges to Quizzes entities.
func (_u *LessonsUpdateOne) RemoveQuizzes(v ...*Quizzes) *LessonsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuizzeIDs(ids...)
}

// Where appends a list predicates to the LessonsUpdate builder.
func (_u *LessonsUpdateOne) Where(ps ...predicate.Lessons) *LessonsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LessonsUpdateOne) Select(field string, fields ...string) *LessonsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Lessons entity.
func (_u *LessonsUpdateOne) Save(ctx context.Context) (*Lessons, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LessonsUpdateOne) SaveX(ctx context.Context) *Lessons {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LessonsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LessonsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LessonsUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if lessons.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized lessons.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := lessons.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *LessonsUpdateOne) check() error {
	if _u.mutation.SectionsCleared() && len(_u.mutation.SectionsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Lessons.Sections"`)
	}
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Lessons.Courses"`)
	}
	return nil
}

func (_u *LessonsUpdateOne) sqlSave(ctx context.Context) (_node *Lessons, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lessons.Table, lessons.Columns, sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Lessons.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lessons.FieldID)
		for _, f := range fields {
			if !lessons.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lessons.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(lessons.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(lessons.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(lessons.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(lessons.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(lessons.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.VideoURL(); ok {
		_spec.SetField(lessons.FieldVideoURL, field.TypeString, value)
	}
	if _u.mutation.VideoURLCleared() {
		_spec.ClearField(lessons.FieldVideoURL, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(lessons.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(lessons.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(lessons.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(lessons.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPreview(); ok {
		_spec.SetField(lessons.FieldIsPreview, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lessons.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessons.SectionsTable,
			Columns: []string{lessons.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessons.SectionsTable,
			Columns: []string{lessons.SectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessons.CoursesTable,
			Columns: []string{lessons.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lessons.CoursesTable,
			Columns: []string{lessons.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonProgressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.LessonProgressesTable,
			Columns: []string{lessons.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLessonProgressesIDs(); len(nodes) > 0 && !_u.mutation.LessonProgressesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.LessonProgressesTable,
			Columns: []string{lessons.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonProgressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.LessonProgressesTable,
			Columns: []string{lessons.LessonProgressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessonprogresses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.QuizzesTable,
			Columns: []string{lessons.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuizzesIDs(); len(nodes) > 0 && !_u.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.QuizzesTable,
			Columns: []string{lessons.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lessons.QuizzesTable,
			Columns: []string{lessons.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Lessons{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lessons.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
