// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-backend/ent/questions"
	"lms-backend/ent/quizzes"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionsCreate is the builder for creating a Questions entity.
type QuestionsCreate struct {
	config
	mutation *QuestionsMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *QuestionsCreate) SetDeletedAt(v time.Time) *QuestionsCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *QuestionsCreate) SetNillableDeletedAt(v *time.Time) *QuestionsCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetQuizID sets the "quiz_id" field.
func (_c *QuestionsCreate) SetQuizID(v int) *QuestionsCreate {
	_c.mutation.SetQuizID(v)
	return _c
}

// SetQuestionText sets the "question_text" field.
func (_c *QuestionsCreate) SetQuestionText(v string) *QuestionsCreate {
	_c.mutation.SetQuestionText(v)
	return _c
}

// SetOptionA sets the "option_a" field.
func (_c *QuestionsCreate) SetOptionA(v string) *QuestionsCreate {
	_c.mutation.SetOptionA(v)
	return _c
}

// SetOptionB sets the "option_b" field.
func (_c *QuestionsCreate) SetOptionB(v string) *QuestionsCreate {
	_c.mutation.SetOptionB(v)
	return _c
}

// SetOptionC sets the "option_c" field.
func (_c *QuestionsCreate) SetOptionC(v string) *QuestionsCreate {
	_c.mutation.SetOptionC(v)
	return _c
}

// SetOptionD sets the "option_d" field.
func (_c *QuestionsCreate) SetOptionD(v string) *QuestionsCreate {
	_c.mutation.SetOptionD(v)
	return _c
}

// SetCorrectOption sets the "correct_option" field.
func (_c *QuestionsCreate) SetCorrectOption(v questions.CorrectOption) *QuestionsCreate {
	_c.mutation.SetCorrectOption(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuestionsCreate) SetCreatedAt(v time.Time) *QuestionsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuestionsCreate) SetNillableCreatedAt(v *time.Time) *QuestionsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuestionsCreate) SetUpdatedAt(v time.Time) *QuestionsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuestionsCreate) SetNillableUpdatedAt(v *time.Time) *QuestionsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetQuizzesID sets the "Quizzes" edge to the Quizzes entity by ID.
func (_c *QuestionsCreate) SetQuizzesID(id int) *QuestionsCreate {
	_c.mutation.SetQuizzesID(id)
	return _c
}

// SetQuizzes sets the "Quizzes" edge to the Quizzes entity.
func (_c *QuestionsCreate) SetQuizzes(v *Quizzes) *QuestionsCreate {
	return _c.SetQuizzesID(v.ID)
}

// Mutation returns the QuestionsMutation object of the builder.
func (_c *QuestionsCreate) Mutation() *QuestionsMutation {
	return _c.mutation
}

// Save creates the Questions in the database.
func (_c *QuestionsCreate) Save(ctx context.Context) (*Questions, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuestionsCreate) SaveX(ctx context.Context) *Questions {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestionsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestionsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuestionsCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if questions.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized questions.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := questions.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if questions.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized questions.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := questions.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuestionsCreate) check() error {
	if _, ok := _c.mutation.QuizID(); !ok {
		return &ValidationError{Name: "quiz_id", err: errors.New(`ent: missing required field "Questions.quiz_id"`)}
	}
	if _, ok := _c.mutation.QuestionText(); !ok {
		return &ValidationError{Name: "question_text", err: errors.New(`ent: missing required field "Questions.question_text"`)}
	}
	if _, ok := _c.mutation.OptionA(); !ok {
		return &ValidationError{Name: "option_a", err: errors.New(`ent: missing required field "Questions.option_a"`)}
	}
	if _, ok := _c.mutation.OptionB(); !ok {
		return &ValidationError{Name: "option_b", err: errors.New(`ent: missing required field "Questions.option_b"`)}
	}
	if _, ok := _c.mutation.OptionC(); !ok {
		return &ValidationError{Name: "option_c", err: errors.New(`ent: missing required field "Questions.option_c"`)}
	}
	if _, ok := _c.mutation.OptionD(); !ok {
		return &ValidationError{Name: "option_d", err: errors.New(`ent: missing required field "Questions.option_d"`)}
	}
	if _, ok := _c.mutation.CorrectOption(); !ok {
		return &ValidationError{Name: "correct_option", err: errors.New(`ent: missing required field "Questions.correct_option"`)}
	}
	if v, ok := _c.mutation.CorrectOption(); ok {
		if err := questions.CorrectOptionValidator(v); err != nil {
			return &ValidationError{Name: "correct_option", err: fmt.Errorf(`ent: validator failed for field "Questions.correct_option": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Questions.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Questions.updated_at"`)}
	}
	if len(_c.mutation.QuizzesIDs()) == 0 {
		return &ValidationError{Name: "Quizzes", err: errors.New(`ent: missing required edge "Questions.Quizzes"`)}
	}
	return nil
}

func (_c *QuestionsCreate) sqlSave(ctx context.Context) (*Questions, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuestionsCreate) createSpec() (*Questions, *sqlgraph.CreateSpec) {
	var (
		_node = &Questions{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(questions.Table, sqlgraph.NewFieldSpec(questions.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(questions.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.QuestionText(); ok {
		_spec.SetField(questions.FieldQuestionText, field.TypeString, value)
		_node.QuestionText = value
	}
	if value, ok := _c.mutation.OptionA(); ok {
		_spec.SetField(questions.FieldOptionA, field.TypeString, value)
		_node.OptionA = value
	}
	if value, ok := _c.mutation.OptionB(); ok {
		_spec.SetField(questions.FieldOptionB, field.TypeString, value)
		_node.OptionB = value
	}
	if value, ok := _c.mutation.OptionC(); ok {
		_spec.SetField(questions.FieldOptionC, field.TypeString, value)
		_node.OptionC = value
	}
	if value, ok := _c.mutation.OptionD(); ok {
		_spec.SetField(questions.FieldOptionD, field.TypeString, value)
		_node.OptionD = value
	}
	if value, ok := _c.mutation.CorrectOption(); ok {
		_spec.SetField(questions.FieldCorrectOption, field.TypeEnum, value)
		_node.CorrectOption = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(questions.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(questions.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.QuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questions.QuizzesTable,
			Columns: []string{questions.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.QuizID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuestionsCreateBulk is the builder for creating many Questions entities in bulk.
type QuestionsCreateBulk struct {
	config
	err      error
	builders []*QuestionsCreate
}

// Save creates the Questions entities in the database.
func (_c *QuestionsCreateBulk) Save(ctx context.Context) ([]*Questions, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Questions, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuestionsCreateBulk) SaveX(ctx context.Context) []*Questions {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestionsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestionsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
