// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"lms-backend/ent/predicate"
	"lms-backend/ent/quizzes"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizzesDelete is the builder for deleting a Quizzes entity.
type QuizzesDelete struct {
	config
	hooks    []Hook
	mutation *QuizzesMutation
}

// Where appends a list predicates to the QuizzesDelete builder.
func (_d *QuizzesDelete) Where(ps ...predicate.Quizzes) *QuizzesDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *QuizzesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuizzesDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *QuizzesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(quizzes.Table, sqlgraph.NewFieldSpec(quizzes.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// QuizzesDeleteOne is the builder for deleting a single Quizzes entity.
type QuizzesDeleteOne struct {
	_d *QuizzesDelete
}

// Where appends a list predicates to the QuizzesDelete builder.
func (_d *QuizzesDeleteOne) Where(ps ...predicate.Quizzes) *QuizzesDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *QuizzesDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{quizzes.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuizzesDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
