// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-backend/ent/courses"
	"lms-backend/ent/lessons"
	"lms-backend/ent/sections"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SectionsCreate is the builder for creating a Sections entity.
type SectionsCreate struct {
	config
	mutation *SectionsMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SectionsCreate) SetDeletedAt(v time.Time) *SectionsCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SectionsCreate) SetNillableDeletedAt(v *time.Time) *SectionsCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCourseID sets the "course_id" field.
func (_c *SectionsCreate) SetCourseID(v int) *SectionsCreate {
	_c.mutation.SetCourseID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *SectionsCreate) SetTitle(v string) *SectionsCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *SectionsCreate) SetSortOrder(v int) *SectionsCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *SectionsCreate) SetNillableSortOrder(v *int) *SectionsCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SectionsCreate) SetCreatedAt(v time.Time) *SectionsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SectionsCreate) SetNillableCreatedAt(v *time.Time) *SectionsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SectionsCreate) SetUpdatedAt(v time.Time) *SectionsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SectionsCreate) SetNillableUpdatedAt(v *time.Time) *SectionsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_c *SectionsCreate) SetCoursesID(id int) *SectionsCreate {
	_c.mutation.SetCoursesID(id)
	return _c
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_c *SectionsCreate) SetCourses(v *Courses) *SectionsCreate {
	return _c.SetCoursesID(v.ID)
}

// AddLessonIDs adds the "Lessons" edge to the Lessons entity by IDs.
func (_c *SectionsCreate) AddLessonIDs(ids ...int) *SectionsCreate {
	_c.mutation.AddLessonIDs(ids...)
	return _c
}

// AddLessons adds the "Lessons" edges to the Lessons entity.
func (_c *SectionsCreate) AddLessons(v ...*Lessons) *SectionsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLessonIDs(ids...)
}

// Mutation returns the SectionsMutation object of the builder.
func (_c *SectionsCreate) Mutation() *SectionsMutation {
	return _c.mutation
}

// Save creates the Sections in the database.
func (_c *SectionsCreate) Save(ctx context.Context) (*Sections, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SectionsCreate) SaveX(ctx context.Context) *Sections {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SectionsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SectionsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SectionsCreate) defaults() error {
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := sections.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sections.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sections.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sections.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if sections.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sections.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sections.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SectionsCreate) check() error {
	if _, ok := _c.mutation.CourseID(); !ok {
		return &ValidationError{Name: "course_id", err: errors.New(`ent: missing required field "Sections.course_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Sections.title"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Sections.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Sections.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Sections.updated_at"`)}
	}
	if len(_c.mutation.CoursesIDs()) == 0 {
		return &ValidationError{Name: "Courses", err: errors.New(`ent: missing required edge "Sections.Courses"`)}
	}
	return nil
}

func (_c *SectionsCreate) sqlSave(ctx context.Context) (*Sections, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SectionsCreate) createSpec() (*Sections, *sqlgraph.CreateSpec) {
	var (
		_node = &Sections{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sections.Table, sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sections.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(sections.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(sections.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sections.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sections.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sections.CoursesTable,
			Columns: []string{sections.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CourseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sections.LessonsTable,
			Columns: []string{sections.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SectionsCreateBulk is the builder for creating many Sections entities in bulk.
type SectionsCreateBulk struct {
	config
	err      error
	builders []*SectionsCreate
}

// Save creates the Sections entities in the database.
func (_c *SectionsCreateBulk) Save(ctx context.Context) ([]*Sections, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Sections, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SectionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SectionsCreateBulk) SaveX(ctx context.Context) []*Sections {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SectionsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SectionsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
