// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-backend/ent/courses"
	"lms-backend/ent/lessons"
	"lms-backend/ent/predicate"
	"lms-backend/ent/sections"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SectionsUpdate is the builder for updating Sections entities.
type SectionsUpdate struct {
	config
	hooks    []Hook
	mutation *SectionsMutation
}

// Where appends a list predicates to the SectionsUpdate builder.
func (_u *SectionsUpdate) Where(ps ...predicate.Sections) *SectionsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SectionsUpdate) SetDeletedAt(v time.Time) *SectionsUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SectionsUpdate) SetNillableDeletedAt(v *time.Time) *SectionsUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SectionsUpdate) ClearDeletedAt() *SectionsUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *SectionsUpdate) SetCourseID(v int) *SectionsUpdate {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *SectionsUpdate) SetNillableCourseID(v *int) *SectionsUpdate {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SectionsUpdate) SetTitle(v string) *SectionsUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SectionsUpdate) SetNillableTitle(v *string) *SectionsUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SectionsUpdate) SetSortOrder(v int) *SectionsUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SectionsUpdate) SetNillableSortOrder(v *int) *SectionsUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SectionsUpdate) AddSortOrder(v int) *SectionsUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SectionsUpdate) SetUpdatedAt(v time.Time) *SectionsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *SectionsUpdate) SetCoursesID(id int) *SectionsUpdate {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *SectionsUpdate) SetCourses(v *Courses) *SectionsUpdate {
	return _u.SetCoursesID(v.ID)
}

// AddLessonIDs adds the "Lessons" edge to the Lessons entity by IDs.
func (_u *SectionsUpdate) AddLessonIDs(ids ...int) *SectionsUpdate {
	_u.mutation.AddLessonIDs(ids...)
	return _u
}

// AddLessons adds the "Lessons" edges to the Lessons entity.
func (_u *SectionsUpdate) AddLessons(v ...*Lessons) *SectionsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLessonIDs(ids...)
}

// Mutation returns the SectionsMutation object of the builder.
func (_u *SectionsUpdate) Mutation() *SectionsMutation {
	return _u.mutation
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *SectionsUpdate) ClearCourses() *SectionsUpdate {
	_u.mutation.ClearCourses()
	return _u
}

// ClearLessons clears all "Lessons" edges to the Lessons entity.
func (_u *SectionsUpdate) ClearLessons() *SectionsUpdate {
	_u.mutation.ClearLessons()
	return _u
}

// RemoveLessonIDs removes the "Lessons" edge to Lessons entities by IDs.
func (_u *SectionsUpdate) RemoveLessonIDs(ids ...int) *SectionsUpdate {
	_u.mutation.RemoveLessonIDs(ids...)
	return _u
}

// RemoveLessons removes "Lessons" edges to Lessons entities.
func (_u *SectionsUpdate) RemoveLessons(v ...*Lessons) *SectionsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLessonIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SectionsUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectionsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SectionsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectionsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SectionsUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sections.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sections.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sections.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SectionsUpdate) check() error {
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sections.Courses"`)
	}
	return nil
}

func (_u *SectionsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sections.Table, sections.Columns, sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sections.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sections.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(sections.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(sections.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(sections.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sections.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sections.CoursesTable,
			Columns: []string{sections.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sections.CoursesTable,
			Columns: []string{sections.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sections.LessonsTable,
			Columns: []string{sections.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLessonsIDs(); len(nodes) > 0 && !_u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sections.LessonsTable,
			Columns: []string{sections.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sections.LessonsTable,
			Columns: []string{sections.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sections.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SectionsUpdateOne is the builder for updating a single Sections entity.
type SectionsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SectionsMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SectionsUpdateOne) SetDeletedAt(v time.Time) *SectionsUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SectionsUpdateOne) SetNillableDeletedAt(v *time.Time) *SectionsUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SectionsUpdateOne) ClearDeletedAt() *SectionsUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *SectionsUpdateOne) SetCourseID(v int) *SectionsUpdateOne {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *SectionsUpdateOne) SetNillableCourseID(v *int) *SectionsUpdateOne {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SectionsUpdateOne) SetTitle(v string) *SectionsUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SectionsUpdateOne) SetNillableTitle(v *string) *SectionsUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SectionsUpdateOne) SetSortOrder(v int) *SectionsUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SectionsUpdateOne) SetNillableSortOrder(v *int) *SectionsUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SectionsUpdateOne) AddSortOrder(v int) *SectionsUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SectionsUpdateOne) SetUpdatedAt(v time.Time) *SectionsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCoursesID sets the "Courses" edge to the Courses entity by ID.
func (_u *SectionsUpdateOne) SetCoursesID(id int) *SectionsUpdateOne {
	_u.mutation.SetCoursesID(id)
	return _u
}

// SetCourses sets the "Courses" edge to the Courses entity.
func (_u *SectionsUpdateOne) SetCourses(v *Courses) *SectionsUpdateOne {
	return _u.SetCoursesID(v.ID)
}

// AddLessonIDs adds the "Lessons" edge to the Lessons entity by IDs.
func (_u *SectionsUpdateOne) AddLessonIDs(ids ...int) *SectionsUpdateOne {
	_u.mutation.AddLessonIDs(ids...)
	return _u
}

// AddLessons adds the "Lessons" edges to the Lessons entity.
func (_u *SectionsUpdateOne) AddLessons(v ...*Lessons) *SectionsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLessonIDs(ids...)
}

// Mutation returns the SectionsMutation object of the builder.
func (_u *SectionsUpdateOne) Mutation() *SectionsMutation {
	return _u.mutation
}

// ClearCourses clears the "Courses" edge to the Courses entity.
func (_u *SectionsUpdateOne) ClearCourses() *SectionsUpdateOne {
	_u.mutation.ClearCourses()
	return _u
}

// ClearLessons clears all "Lessons" edges to the Lessons entity.
func (_u *SectionsUpdateOne) ClearLessons() *SectionsUpdateOne {
	_u.mutation.ClearLessons()
	return _u
}

// RemoveLessonIDs removes the "Lessons" edge to Lessons entities by IDs.
func (_u *SectionsUpdateOne) RemoveLessonIDs(ids ...int) *SectionsUpdateOne {
	_u.mutation.RemoveLessonIDs(ids...)
	return _u
}

// RemoveLessons removes "Lessons" edges to Lessons entities.
func (_u *SectionsUpdateOne) RemoveLessons(v ...*Lessons) *SectionsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLessonIDs(ids...)
}

// Where appends a list predicates to the SectionsUpdate builder.
func (_u *SectionsUpdateOne) Where(ps ...predicate.Sections) *SectionsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SectionsUpdateOne) Select(field string, fields ...string) *SectionsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sections entity.
func (_u *SectionsUpdateOne) Save(ctx context.Context) (*Sections, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectionsUpdateOne) SaveX(ctx context.Context) *Sections {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SectionsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectionsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SectionsUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sections.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sections.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sections.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SectionsUpdateOne) check() error {
	if _u.mutation.CoursesCleared() && len(_u.mutation.CoursesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sections.Courses"`)
	}
	return nil
}

func (_u *SectionsUpdateOne) sqlSave(ctx context.Context) (_node *Sections, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sections.Table, sections.Columns, sqlgraph.NewFieldSpec(sections.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sections.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sections.FieldID)
		for _, f := range fields {
			if !sections.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sections.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sections.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sections.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(sections.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(sections.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(sections.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sections.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CoursesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sections.CoursesTable,
			Columns: []string{sections.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoursesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sections.CoursesTable,
			Columns: []string{sections.CoursesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(courses.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sections.LessonsTable,
			Columns: []string{sections.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLessonsIDs(); len(nodes) > 0 && !_u.mutation.LessonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sections.LessonsTable,
			Columns: []string{sections.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sections.LessonsTable,
			Columns: []string{sections.LessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lessons.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sections{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sections.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
