// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"lms-worker/ent/migrate"

	"lms-worker/ent/categories"
	"lms-worker/ent/courses"
	"lms-worker/ent/notifications"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Categories is the client for interacting with the Categories builders.
	Categories *CategoriesClient
	// Courses is the client for interacting with the Courses builders.
	Courses *CoursesClient
	// Notifications is the client for interacting with the Notifications builders.
	Notifications *NotificationsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Categories = NewCategoriesClient(c.config)
	c.Courses = NewCoursesClient(c.config)
	c.Notifications = NewNotificationsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Categories:    NewCategoriesClient(cfg),
		Courses:       NewCoursesClient(cfg),
		Notifications: NewNotificationsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Categories:    NewCategoriesClient(cfg),
		Courses:       NewCoursesClient(cfg),
		Notifications: NewNotificationsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Categories.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Categories.Use(hooks...)
	c.Courses.Use(hooks...)
	c.Notifications.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Categories.Intercept(interceptors...)
	c.Courses.Intercept(interceptors...)
	c.Notifications.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CategoriesMutation:
		return c.Categories.mutate(ctx, m)
	case *CoursesMutation:
		return c.Courses.mutate(ctx, m)
	case *NotificationsMutation:
		return c.Notifications.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CategoriesClient is a client for the Categories schema.
type CategoriesClient struct {
	config
}

// NewCategoriesClient returns a client for the Categories from the given config.
func NewCategoriesClient(c config) *CategoriesClient {
	return &CategoriesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `categories.Hooks(f(g(h())))`.
func (c *CategoriesClient) Use(hooks ...Hook) {
	c.hooks.Categories = append(c.hooks.Categories, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `categories.Intercept(f(g(h())))`.
func (c *CategoriesClient) Intercept(interceptors ...Interceptor) {
	c.inters.Categories = append(c.inters.Categories, interceptors...)
}

// Create returns a builder for creating a Categories entity.
func (c *CategoriesClient) Create() *CategoriesCreate {
	mutation := newCategoriesMutation(c.config, OpCreate)
	return &CategoriesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Categories entities.
func (c *CategoriesClient) CreateBulk(builders ...*CategoriesCreate) *CategoriesCreateBulk {
	return &CategoriesCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CategoriesClient) MapCreateBulk(slice any, setFunc func(*CategoriesCreate, int)) *CategoriesCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CategoriesCreateBulk{err: fmt.Errorf("calling to CategoriesClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CategoriesCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CategoriesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Categories.
func (c *CategoriesClient) Update() *CategoriesUpdate {
	mutation := newCategoriesMutation(c.config, OpUpdate)
	return &CategoriesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CategoriesClient) UpdateOne(_m *Categories) *CategoriesUpdateOne {
	mutation := newCategoriesMutation(c.config, OpUpdateOne, withCategories(_m))
	return &CategoriesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CategoriesClient) UpdateOneID(id int) *CategoriesUpdateOne {
	mutation := newCategoriesMutation(c.config, OpUpdateOne, withCategoriesID(id))
	return &CategoriesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Categories.
func (c *CategoriesClient) Delete() *CategoriesDelete {
	mutation := newCategoriesMutation(c.config, OpDelete)
	return &CategoriesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CategoriesClient) DeleteOne(_m *Categories) *CategoriesDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CategoriesClient) DeleteOneID(id int) *CategoriesDeleteOne {
	builder := c.Delete().Where(categories.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CategoriesDeleteOne{builder}
}

// Query returns a query builder for Categories.
func (c *CategoriesClient) Query() *CategoriesQuery {
	return &CategoriesQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCategories},
		inters: c.Interceptors(),
	}
}

// Get returns a Categories entity by its id.
func (c *CategoriesClient) Get(ctx context.Context, id int) (*Categories, error) {
	return c.Query().Where(categories.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CategoriesClient) GetX(ctx context.Context, id int) *Categories {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCourses queries the Courses edge of a Categories.
func (c *CategoriesClient) QueryCourses(_m *Categories) *CoursesQuery {
	query := (&CoursesClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(categories.Table, categories.FieldID, id),
			sqlgraph.To(courses.Table, courses.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, categories.CoursesTable, categories.CoursesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CategoriesClient) Hooks() []Hook {
	return c.hooks.Categories
}

// Interceptors returns the client interceptors.
func (c *CategoriesClient) Interceptors() []Interceptor {
	return c.inters.Categories
}

func (c *CategoriesClient) mutate(ctx context.Context, m *CategoriesMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CategoriesCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CategoriesUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CategoriesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CategoriesDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Categories mutation op: %q", m.Op())
	}
}

// CoursesClient is a client for the Courses schema.
type CoursesClient struct {
	config
}

// NewCoursesClient returns a client for the Courses from the given config.
func NewCoursesClient(c config) *CoursesClient {
	return &CoursesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `courses.Hooks(f(g(h())))`.
func (c *CoursesClient) Use(hooks ...Hook) {
	c.hooks.Courses = append(c.hooks.Courses, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `courses.Intercept(f(g(h())))`.
func (c *CoursesClient) Intercept(interceptors ...Interceptor) {
	c.inters.Courses = append(c.inters.Courses, interceptors...)
}

// Create returns a builder for creating a Courses entity.
func (c *CoursesClient) Create() *CoursesCreate {
	mutation := newCoursesMutation(c.config, OpCreate)
	return &CoursesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Courses entities.
func (c *CoursesClient) CreateBulk(builders ...*CoursesCreate) *CoursesCreateBulk {
	return &CoursesCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CoursesClient) MapCreateBulk(slice any, setFunc func(*CoursesCreate, int)) *CoursesCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CoursesCreateBulk{err: fmt.Errorf("calling to CoursesClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CoursesCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CoursesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Courses.
func (c *CoursesClient) Update() *CoursesUpdate {
	mutation := newCoursesMutation(c.config, OpUpdate)
	return &CoursesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CoursesClient) UpdateOne(_m *Courses) *CoursesUpdateOne {
	mutation := newCoursesMutation(c.config, OpUpdateOne, withCourses(_m))
	return &CoursesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CoursesClient) UpdateOneID(id int) *CoursesUpdateOne {
	mutation := newCoursesMutation(c.config, OpUpdateOne, withCoursesID(id))
	return &CoursesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Courses.
func (c *CoursesClient) Delete() *CoursesDelete {
	mutation := newCoursesMutation(c.config, OpDelete)
	return &CoursesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CoursesClient) DeleteOne(_m *Courses) *CoursesDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CoursesClient) DeleteOneID(id int) *CoursesDeleteOne {
	builder := c.Delete().Where(courses.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CoursesDeleteOne{builder}
}

// Query returns a query builder for Courses.
func (c *CoursesClient) Query() *CoursesQuery {
	return &CoursesQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCourses},
		inters: c.Interceptors(),
	}
}

// Get returns a Courses entity by its id.
func (c *CoursesClient) Get(ctx context.Context, id int) (*Courses, error) {
	return c.Query().Where(courses.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CoursesClient) GetX(ctx context.Context, id int) *Courses {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCategories queries the Categories edge of a Courses.
func (c *CoursesClient) QueryCategories(_m *Courses) *CategoriesQuery {
	query := (&CategoriesClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(courses.Table, courses.FieldID, id),
			sqlgraph.To(categories.Table, categories.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, courses.CategoriesTable, courses.CategoriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CoursesClient) Hooks() []Hook {
	return c.hooks.Courses
}

// Interceptors returns the client interceptors.
func (c *CoursesClient) Interceptors() []Interceptor {
	return c.inters.Courses
}

func (c *CoursesClient) mutate(ctx context.Context, m *CoursesMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CoursesCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CoursesUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CoursesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CoursesDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Courses mutation op: %q", m.Op())
	}
}

// NotificationsClient is a client for the Notifications schema.
type NotificationsClient struct {
	config
}

// NewNotificationsClient returns a client for the Notifications from the given config.
func NewNotificationsClient(c config) *NotificationsClient {
	return &NotificationsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notifications.Hooks(f(g(h())))`.
func (c *NotificationsClient) Use(hooks ...Hook) {
	c.hooks.Notifications = append(c.hooks.Notifications, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notifications.Intercept(f(g(h())))`.
func (c *NotificationsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Notifications = append(c.inters.Notifications, interceptors...)
}

// Create returns a builder for creating a Notifications entity.
func (c *NotificationsClient) Create() *NotificationsCreate {
	mutation := newNotificationsMutation(c.config, OpCreate)
	return &NotificationsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Notifications entities.
func (c *NotificationsClient) CreateBulk(builders ...*NotificationsCreate) *NotificationsCreateBulk {
	return &NotificationsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationsClient) MapCreateBulk(slice any, setFunc func(*NotificationsCreate, int)) *NotificationsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationsCreateBulk{err: fmt.Errorf("calling to NotificationsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Notifications.
func (c *NotificationsClient) Update() *NotificationsUpdate {
	mutation := newNotificationsMutation(c.config, OpUpdate)
	return &NotificationsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationsClient) UpdateOne(_m *Notifications) *NotificationsUpdateOne {
	mutation := newNotificationsMutation(c.config, OpUpdateOne, withNotifications(_m))
	return &NotificationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationsClient) UpdateOneID(id int) *NotificationsUpdateOne {
	mutation := newNotificationsMutation(c.config, OpUpdateOne, withNotificationsID(id))
	return &NotificationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Notifications.
func (c *NotificationsClient) Delete() *NotificationsDelete {
	mutation := newNotificationsMutation(c.config, OpDelete)
	return &NotificationsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationsClient) DeleteOne(_m *Notifications) *NotificationsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationsClient) DeleteOneID(id int) *NotificationsDeleteOne {
	builder := c.Delete().Where(notifications.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationsDeleteOne{builder}
}

// Query returns a query builder for Notifications.
func (c *NotificationsClient) Query() *NotificationsQuery {
	return &NotificationsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotifications},
		inters: c.Interceptors(),
	}
}

// Get returns a Notifications entity by its id.
func (c *NotificationsClient) Get(ctx context.Context, id int) (*Notifications, error) {
	return c.Query().Where(notifications.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationsClient) GetX(ctx context.Context, id int) *Notifications {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NotificationsClient) Hooks() []Hook {
	return c.hooks.Notifications
}

// Interceptors returns the client interceptors.
func (c *NotificationsClient) Interceptors() []Interceptor {
	return c.inters.Notifications
}

func (c *NotificationsClient) mutate(ctx context.Context, m *NotificationsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Notifications mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Categories, Courses, Notifications []ent.Hook
	}
	inters struct {
		Categories, Courses, Notifications []ent.Interceptor
	}
)
